content = """
══════════════════════════════════════════════════════════
SECTION 3: FIRST 48 HOURS IN DARKNESS (Prompts 45–88 | 1:28–2:56)
══════════════════════════════════════════════════════════

PROMPT 45 [1:28–1:30]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman sits on a simple chair — a rectangle seat on four legs. The stickman: medium circle head tilted forward slightly (chin angled down), two dot eyes looking downward (dots in the lower portion of the head circle), a short flat horizontal mouth (contemplative). Body line sits above the chair rectangle (perched). Both arms resting on thighs (sticks angled downward at 45 degrees, ending at the leg sticks — seated arm position). Legs bent at the knee (lower leg sticks angled backward under the chair). Around the stickman in the white space: three floating word labels in black caps — "HUNGER?" to the upper left, "TIRED?" to the upper right, "WHAT TIME?" below. Bold black question marks after each word. Text at top: "HOUR 24." Flat colour, MS Paint doodle style.

PROMPT 46 [1:30–1:32]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A large simple analogue clock face — thick black circle outline, white fill, twelve tick marks. The clock hands are melting — both hands are drawn as wavy drooping lines rather than straight, dripping downward like a Dalí-style MS Paint doodle. The numerals on the face are also wobbly and uneven. A stickman stands beside the melting clock, one hand pressed flat against the clock face: medium circle head, wide dot eyes (alarmed), downturned curved mouth (distressed), body upright, right arm extended to touch the clock face (arm stick pressed flat against the circle outline of the clock), left arm at side, legs together. Text below: "TIME IS MELTING." Flat colour, MS Paint doodle style.

PROMPT 47 [1:32–1:34]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A simple brain shape (yellow oval, fold lines) hovers at the centre of the frame. From the brain, four arrows point in four cardinal directions, but each arrow has a different colour and label. TOP arrow (black): "AWAKE SIGNAL ↑." BOTTOM arrow (navy): "SLEEP SIGNAL ↑." LEFT arrow (red): "CONFUSION ↑." RIGHT arrow (green): "HUNGER SIGNAL ↑." All signals firing simultaneously — the arrows are bold with solid arrowheads. The brain appears overwhelmed — MS Paint style, the brain outline itself is slightly wavy (shaking). Text at top: "CONFLICTING SIGNALS." No stickman. Flat colour, MS Paint doodle style.

PROMPT 48 [1:34–1:36]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman lies on a simple horizontal line (the floor), not in a bed — just lying flat on the ground. The stickman: medium circle head lying to the side, two dot eyes that are half open and half closed (dots at the very bottom of the eye area — barely awake), a flat straight mouth. Body line horizontal along the floor. Arms spread loosely to the sides (arm sticks extending at low angles from the body). Legs slightly apart and relaxed. Above the lying figure, a speech bubble reading: "AM I TIRED OR AWAKE?" A jagged red thought-burst shape (like a starburst with points) overlaps the speech bubble for emphasis. Text at the top: "HOUR 30." Flat colour, MS Paint doodle style.

PROMPT 49 [1:36–1:38]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman stands looking at a simple plate of food on a table. Table: a horizontal line on two vertical legs. On the table: a circle outline (the plate) with simple food doodles inside (a small triangle for a sandwich, a circle for an apple). The stickman: medium circle head, dot eyes directed at the plate, an expression of uncertainty — eyes slightly narrowed (dots with small curved lines above — furrowed brows), mouth a small downward curved line (not hunger but confusion). Right arm extends toward the food, hand hovering over the plate (indecisive gesture). Left arm at side. Legs together. A large question mark floats above the plate. Text: "HUNGRY? NOT HUNGRY? CAN'T TELL." Flat colour, MS Paint doodle style.

PROMPT 50 [1:38–1:40]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A split-brain diagram. A brain shape (yellow oval) is divided by a vertical line down the middle into LEFT HALF and RIGHT HALF. LEFT HALF labelled "SAYS: DAY" — contains a small drawn sun. RIGHT HALF labelled "SAYS: NIGHT" — contains a small drawn moon. The two halves are fighting — between them, at the dividing line, bold red lightning bolts (two zigzag lines) crackle. Text above: "YOUR BRAIN IS ARGUING WITH ITSELF." Below the brain: a small stickman looking up at the brain in frustration. The stickman: small circle head, dot eyes directed upward, both arms raised at head height (exasperated gesture — arms up and bent), legs apart. Flat colour, MS Paint doodle style.

PROMPT 51 [1:40–1:42]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman experiencing a visual effect. The stickman stands centre: medium circle head, dot eyes wide and startled (large dot circles, positioned at the outer edges of the head — eyes wide with shock), an open O-shaped mouth (gasping). Body upright. Both arms instinctively raised to shoulder height (the hands are near the face — a startled recoil). Legs stepping back — right leg back, left leg forward (recoiling backward step). In front of the stickman's face, in the white space: six small starburst/spark shapes in flat yellow — drawn as irregular star bursts with four to six points each, scattered in a cluster. A label beside the cluster: "PHOSPHENES." Text at top: "HOUR 36 — LIGHTS WITHOUT LIGHT." Flat colour, MS Paint doodle style.

PROMPT 52 [1:42–1:44]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. An eye diagram (large oval eye shape, iris circle, pupil dot) — the eye is CLOSED in darkness (two curved lines meeting to form a closed eye outline). FROM INSIDE the closed eye, small starburst flashes radiate OUTWARD through the closed eyelid — drawn as small spike shapes piercing the closed eyelid outline. A label beside: "VISUAL CORTEX FIRING." An arrow from outside the eye pointing to the retina: "NO SIGNAL ENTERING." A bold "BUT →" connector leads to the radiating flashes: "BRAIN GENERATING OWN LIGHT." No stickman. Infographic style, flat colour, MS Paint doodle style.

PROMPT 53 [1:44–1:46]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A brain shape (yellow oval with fold lines) sits at the top of the frame. At the back of the brain, a specific region is outlined with a dotted circle and labelled "VISUAL CORTEX." Inside this outlined region, multiple small lightning bolt symbols flash (indicating electrical activity). From the visual cortex region, dotted lines extend FORWARD (toward the front of the brain) — suggesting signals are being generated internally. Text beside: "MAKING PICTURES FROM NOTHING." No stickman. Clean diagram, flat yellow on white, MS Paint doodle style.

PROMPT 54 [1:46–1:48]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman stands facing the viewer, hands over eyes. The stickman: medium circle head, BOTH arms raised to face level (both sticks pressed against the eye area of the head circle — hands covering eyes). Legs together, standing upright. Despite the hands covering the eyes: from BEHIND the hands (from inside the head), small starburst light shapes radiate OUTWARD and AROUND the covering hands — the light is coming FROM INSIDE, not from outside. A label: "YOU SEE LIGHTS IN TOTAL DARK." An arrow pointing to the radiating bursts: "BRAIN-GENERATED." Flat colour, yellow starbursts, black outlines on white, MS Paint doodle style.

PROMPT 55 [1:48–1:50]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A sound wave infographic adapted for the visual system. A simple wave symbol (three concentric arcs — like a WiFi symbol rotated sideways) in yellow represents a "signal." To the LEFT of the wave: an empty socket shape — no plug connected (labelled "RETINA: NO INPUT"). To the RIGHT: a brain shape (yellow oval) with the wave entering it — but the wave entering the brain is ALSO originating from the brain itself (arrows both entering and leaving the same side). Text: "THE BRAIN CANNOT TOLERATE SILENCE." A red X over the empty socket. Flat colour, MS Paint doodle style.

PROMPT 56 [1:50–1:52]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman in a darkened environment — the upper three-quarters of the frame is filled with flat navy blue. The stickman stands at the boundary between the white floor and the navy dark above: medium circle head at the navy-white border, two very large dot eyes (large filled black circles — pupils fully dilated in dark), a small uncertain downturned line mouth. Body below in the white. Both arms at sides. Legs apart. From the eye area of the head, two thin dotted lines extend UPWARD into the navy dark — reaching outward, searching for something to see, but the navy dark is empty. Text in white caps inside the navy area: "HOUR 40." Flat colour, MS Paint doodle style.

PROMPT 57 [1:52–1:54]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman kneeling on one knee, both hands pressed to the sides of the head (both stick arms raised and bent, hands pressed to either side of the head circle — headache gesture). The stickman: medium circle head, dot eyes pressed shut (two short horizontal dashes — the squinting closed-eye), a strongly downturned curved mouth (pain, distress). Single vertical body tilted slightly forward. One leg kneeling (bent lower leg under), one leg partially upright. Around the head: three concentric thick ring shapes in red radiating outward from the head (indicating a headache/pressure sensation — drawn as concentric ovals, red outline only, no fill). Text: "HEADACHE — HOUR 40." Flat colour, red and black on white, MS Paint doodle style.

PROMPT 58 [1:54–1:56]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. An anatomy-style diagram of the brain (yellow oval, fold lines). A dotted-outline clock shape overlaid on the brain — but the clock hands are loose, floating free from the centre pin, drifting at wrong angles (not pointing to any coherent time). The clock hands are drawn separately from each other, each at a different random angle. Surrounding the brain-clock overlap: the word "DRIFT" appears four times in red at different angles around the brain. Text below: "THE CLOCK IS UNTETHERING." Flat colour, MS Paint doodle style.

PROMPT 59 [1:56–1:58]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A horizontal bar chart — four bars side by side, each representing a different internal body signal. BAR 1 labelled "HUNGER": tall bar reaching 80% height. BAR 2 labelled "FATIGUE": tall bar reaching 90% height. BAR 3 labelled "CONFUSION": bar reaching 95% height (almost full). BAR 4 labelled "TIME SENSE": a bar that barely registers — 5% height (nearly empty). All bars are flat yellow with black outlines. The "TIME SENSE" bar is highlighted with a red circle around it. Text at top: "WHAT YOUR BRAIN CAN STILL TRACK." Flat colour, MS Paint doodle style.

PROMPT 60 [1:58–2:00]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman sitting on the floor (no furniture) — cross-legged pose: body line in the middle, legs drawn as two sticks crossing in front at the floor level. The stickman: medium circle head, dot eyes directed downward and forward (looking at nothing, staring into space), a completely flat horizontal line mouth (blank, dissociated). Arms resting on the leg sticks (both sticks angled inward toward the lap). The white background has a slight speckle effect at the edges (tiny scattered dots in very light navy — suggesting the darkness pressing in at the periphery). Text at the top: "HOUR 48." The text is slightly faded (not full black — lighter weight) suggesting a dimming world. Flat colour, MS Paint doodle style.

PROMPT 61 [2:00–2:02]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A large outline of a human brain (yellow oval, thick fold lines). The outline itself has started to slightly blur at the edges — achieved in MS Paint style by making the outline slightly wobbly and adding ghost-line duplicates offset by a few pixels (suggesting vibration or instability). Inside the brain: the SCN region (lower centre, a small square) is now outlined in red with the text "SIGNAL LOST" beside it. A red X is inside the SCN square. Text above the brain: "HOUR 48: THE MASTER CLOCK IS DRIFTING." No stickman. Flat colour, MS Paint doodle style.

PROMPT 62 [2:02–2:04]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman standing at a wall (a vertical black line on the left represents the wall). The stickman presses both palms flat against the wall: medium circle head turned sideways in profile (a half-oval for the profile view, with one dot eye visible), a small profile nose bump, a slight downward line for mouth. Both arms extended forward and pressed flat against the wall. Legs apart, bracing. The wall has no windows, no door. The rest of the frame is white. Text to the right of the stickman: "SEARCHING FOR UP AND DOWN." Below: "PROPRIOCEPTION FAILING." Flat colour, MS Paint doodle style.

PROMPT 63 [2:04–2:06]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman walking with exaggerated caution — one arm extended forward (feeling the way), one arm extended slightly back for balance. The stickman: medium circle head, two dot eyes directed downward (watching each step), a tense straight-line mouth. Body upright. Front arm (right) extended forward at chest height, palm open (feeling the air ahead). Back arm (left) extended slightly behind and down for balance. Front leg raised mid-step (knee bent upward, lower leg forward). Back leg planted. The floor is indicated by a horizontal line. Text: "NAVIGATING BY MEMORY." Flat colour, MS Paint doodle style.

PROMPT 64 [2:06–2:08]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. An infographic showing the REM sleep architecture. A horizontal axis labelled "TIME SLEEPING." A vertical axis labelled "SLEEP DEPTH." Normally, the sleep waves are drawn as a smooth regular descending staircase-then-rise pattern (shown in faded grey on the left for reference). But the ACTUAL dark-sleep wave (drawn in bold navy blue) is chaotic — the peaks and troughs are irregular, missing expected REM sections (flat spots where REM should be), and plunging too deep and too early. A red circle highlights the abnormal flat section: "REM GONE." No stickman. Flat colour, MS Paint doodle style.

PROMPT 65 [2:08–2:10]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman in bed experiencing vivid dreams. The stickman: medium circle head (lying on pillow — tilted), eyes closed (two curved horizontal dashes — sleeping). Body horizontal. Both arms along body sides. Legs extended. From the head, an ENORMOUS thought/dream bubble extends upward — a massive cloud shape taking up the upper two-thirds of the frame. Inside the cloud: chaotic, densely packed MS Paint doodles — a small running stickman, a jagged monster shape, floating geometric shapes (triangles, circles), a star, a hand reaching. All floating in a jumbled, unsettling arrangement inside the cloud. Text at the top: "DREAMS BECOME VIVID." Flat colour, MS Paint doodle style.

PROMPT 66 [2:10–2:12]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. Same stickman in bed with a dream bubble, but this time the dream bubble content has shifted to disturbing imagery. The stickman: medium circle head, brow slightly furrowed (two diagonal lines above the eyes), mouth a slight downward curve even in sleep — distress seeping in. Inside the dream bubble: three unsettling elements — a large eye with no body floating alone, a mouth with no face (just a curved line of teeth), and a dark heavy shadow-shape (a solid navy amorphous blob). The content is sparse but deeply unnerving. Text: "THEN DISTURBING." Flat colour, navy on white, MS Paint doodle style.

PROMPT 67 [2:12–2:14]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A countdown-style panel. Three boxes arranged vertically: TOP BOX (largest): "HOUR 24 — DISORIENTED" in black. MIDDLE BOX: "HOUR 36 — PHOSPHENES" in navy. BOTTOM BOX: "HOUR 48 — ?" in red with a large question mark. The question mark in the bottom box is extra large and bold. A right-pointing arrow along the left side indicates progression downward. No stickman. Flat colour, MS Paint doodle style.

PROMPT 68 [2:14–2:16]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman stands in the centre of the frame, but their shadow is WRONG — the shadow (drawn as a simple dark navy stick-figure silhouette) points in an unexpected direction (to the right, when the light source, a faint yellow sun in the upper left, would logically cast it leftward). The stickman: medium circle head, dot eyes looking at their own shadow with confusion (eyes directed downward-right toward the shadow), one arm raised to chin (thinking gesture). Legs apart. The wrongly-placed shadow has a red arrow pointing to it: "YOUR PERCEPTION IS OFF." Flat colour, MS Paint doodle style.

PROMPT 69 [2:16–2:18]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman appears to be looking at another version of themselves — a MIRROR IMAGE. But the mirror image stickman is slightly different: the same proportions, but the mirror-image expression is a smile when the original is neutral, or the arms are in a different position. LEFT STICKMAN: medium circle head, straight mouth, arms at sides, legs together. RIGHT STICKMAN (the "reflection"): same medium circle head, upward-curved mouth (smiling), right arm raised slightly. A dotted vertical line between them indicates the mirror plane. Text above: "HOUR 50: WHAT IS REAL?" The divergence between the two figures is subtly unsettling. Flat colour, MS Paint doodle style.

PROMPT 70 [2:18–2:20]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman is pressed to the floor — lying flat face-down. The stickman: medium circle head face-down (the circle outline, with both dot eyes directed straight down into the floor), a wavy line mouth (crushed). Body line along the floor. Both arms spread at shoulder height to the sides (sprawled). Legs slightly apart, lying. Around the figure, multiple arrows with labels point downward: "FATIGUE ↓," "CLARITY ↓," "MOOD ↓," "TEMPERATURE ↓." All arrows are red and pointing downward. Text at the top: "HOUR 52: EVERYTHING DROPPING." Flat colour, red and black on white, MS Paint doodle style.

PROMPT 71 [2:20–2:22]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman stands with both fists raised — a fighting stance, but they're fighting thin air. The stickman: medium circle head, dot eyes wide and intense (two large dot circles, close together in the centre of the face — focused intensity), a tight closed straight-line mouth (determined). Both arms raised at shoulder height, both sticks bent at the elbow, ending in small circle "fists." Legs apart in a wide powerful stance. In front of the fists: nothing — just white space. But above in a speech bubble: "MY BODY SAYS IT'S MORNING." Below the frame: "HOUR 54: FIGHTING THE DARK." Flat colour, MS Paint doodle style.

PROMPT 72 [2:22–2:24]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. An infographic: A large box in the centre divided into two columns. LEFT COLUMN header: "WHAT IS REAL" (black outline box). RIGHT COLUMN header: "WHAT YOUR BRAIN THINKS" (navy outline box). In the LEFT column: a clock showing the actual time 3:00 PM. In the RIGHT column: a clock showing what the brain thinks — 10:00 PM. Below that row: LEFT shows a small sun icon. RIGHT shows a moon icon. The contrast is stark and clear. Below the box: a small stickman stands looking at the box, one arm raised and pointing at the discrepancy: medium circle head, large surprised dot eyes, an open-mouth (O shape), one arm pointing at the right column. Flat colour, MS Paint doodle style.

PROMPT 73 [2:24–2:26]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman sitting on the floor, knees pulled up to chest (both lower leg sticks pulled in, knees up). The stickman: medium circle head resting on knees (head tilted forward and down, resting on the knees), dot eyes looking sideways with a vacant expression (dots directed to the side, one slightly lower than the other), a flat horizontal line mouth (empty). Both arms wrapped around the knees (both sticks curving around the leg area, holding them). The white background has small scattered dots in navy at the periphery of the frame — vignette-style darkness pressing in. Text at the top: "ISOLATION BEGINS TO SETTLE." Flat colour, MS Paint doodle style.

PROMPT 74 [2:26–2:28]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman holding their own head in both hands: medium circle head, both hands clasped on either side of the head (both stick arms bent sharply at 90 degrees upward, sticks pressed flat against either side of the head circle — the "I can't think" posture). Eyes: two dot circles directed straight down (looking at the floor). Mouth: a strong downward curve (genuine distress). Body upright. Legs together. A large speech bubble extending from the head contains only three dots: "..." Flat colour, MS Paint doodle style. Text at top: "HOUR 58: THOUGHTS BECOMING STRANGE."

PROMPT 75 [2:28–2:30]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman standing in the middle of a room (room indicated by a simple floor line and two wall lines at the sides). The stickman is looking at a SHADOW on the wall — the shadow is a stickman silhouette, but the shadow is in a completely different pose than the stickman casting it. The stickman: medium circle head, dot eyes directed at the wall shadow, an alarmed expression — wide eyes, small open O-mouth. Arms at sides. Legs apart. The shadow on the wall: same circle-head stickman but with arms raised and a shape suggesting a different figure altogether. Text below: "THE SHADOWS DON'T MATCH." Flat colour, MS Paint doodle style.

PROMPT 76 [2:30–2:32]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. An infographic panel. A simple thermometer in the upper left (pointing down — temperature low). A clock in the upper right (clock hands melting downward — time sense broken). A heartbeat wave in the lower left (the wave line is normal at the start, then becomes erratic at the right side — rhythms disturbed). A brain shape in the lower right with a large X overlaid (cognition impaired). All four icons are connected to a central starburst shape in the middle that reads "HOUR 60." No stickman. Clean flat infographic, MS Paint doodle style.

PROMPT 77 [2:32–2:34]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. Two stickman figures. LEFT STICKMAN labelled "NORMAL": medium circle head, dot eyes level and clear, slight upward mouth, body upright, both arms at sides, legs apart comfortably. RIGHT STICKMAN labelled "60 HOURS NO LIGHT": same-sized circle head, but dot eyes visibly different — one dot slightly higher than the other (asymmetric, disoriented), a wavy unsettled mouth line, body tilted slightly, one arm raised to the temple, the other arm slightly behind for balance, legs uneven. Between the two: a bold bold arrow pointing from left to right: "→ THIS IS YOUR BRAIN NOW." Flat colour, MS Paint doodle style.

PROMPT 78 [2:34–2:36]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman reaching out toward a wall, touching it tentatively. The stickman: medium circle head, dot eyes directed at the wall (eyes toward the right side of the head), a cautious slightly-open mouth (careful, alert). Right arm fully extended forward, the stick finger touching a flat vertical wall line on the right side of the frame. Left arm slightly out for balance. Left leg forward, right leg behind — cautious step. A speech bubble near the head: "STILL HERE." The word "STILL" is underlined. Text at the top: "GROUNDING BEHAVIOUR — HOUR 62." Flat colour, MS Paint doodle style.

PROMPT 79 [2:36–2:38]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman sits cross-legged on the floor writing in a journal — a small rectangle (the journal/notebook) rests flat on the floor in front of them. The stickman: medium circle head tilted slightly forward and downward (looking at journal), dot eyes directed downward toward the journal, a neutral straight-line mouth (focused concentration). Right arm extends downward from the body, holding a small pen shape (thin stick with a point at the end). Left arm rests on the leg sticks. Legs crossed (two sticks crossing in front at floor level). A speech bubble from the head with text: "DAY 3." Small lines inside the journal rectangle suggest writing. Text at the top: "KEEPING TRACK." Flat colour, MS Paint doodle style.

PROMPT 80 [2:38–2:40]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman holding a small alarm clock up to their ear — listening to it tick. The stickman: medium circle head, dot eyes directed at the clock held up to the right ear, a concentrated neutral mouth (listening hard). Right arm raised to ear height, bent — hand holding the small clock up to the right side of the head. Left arm at side. Legs apart, standing. The small alarm clock has vibration lines on it (indicating ticking sound). A speech bubble from the ear area: "TICK... TICK... TICK..." The text inside the bubble is slightly faded, each word smaller than the last (getting harder to hear or trust). Flat colour, MS Paint doodle style.

PROMPT 81 [2:40–2:42]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman eating from a simple bowl — sitting at a basic table (horizontal line on two short vertical legs). The stickman: medium circle head, dot eyes directed at the bowl, a small upward curve at the corner of the mouth (mild pleasure of eating — tiny comfort in the dark). Right arm bent, holding a simple spoon shape (a stick with a small circle at the end) raised to mouth level. Left arm resting on the table. Legs hanging (seated at table height). The bowl has three short curved lines inside (suggesting food). Text: "MEALS ARE THE ONLY CLOCK LEFT." Flat colour, MS Paint doodle style.

PROMPT 82 [2:42–2:44]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A large speech bubble (cloud shaped, thick black outline) occupies the upper two-thirds of the frame. Inside the bubble: three short lines of handwritten-style text (drawn as irregular wavy horizontal lines — placeholder for writing). Below the bubble, the pointing tail connects to a small stickman's mouth area: small circle head, dot eyes directed straight up at the bubble, a small upward curve mouth (talking). Body below. One arm raised, gesturing while speaking (right arm at 45 degrees upward). Left arm at side. Legs together. Text outside the bubble, pointing into it: "TALKING TO YOURSELF." A secondary label below: "HOUR 65." Flat colour, MS Paint doodle style.

PROMPT 83 [2:44–2:46]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman stands facing away from the viewer — the stickman's back is visible: the circle head (seen from behind — just a circle), the vertical body line, two arm sticks slightly raised, two leg sticks. The back-view stickman looks into a solid navy rectangle filling the right half of the frame. From the navy rectangle, a large eye shape appears — a single drawn eye (oval with iris and pupil) hovering in the dark, looking back at the stickman. The stickman's back-view posture shows tension — arms slightly raised, legs stiff. Text at the top: "THE DARK STARTS LOOKING BACK." Flat colour, MS Paint doodle style.

PROMPT 84 [2:46–2:48]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman asleep in bed, but the dream bubble above is almost completely navy-filled — only the dream content is visible as white shapes on the navy. The stickman: medium circle head tilted on pillow, closed-eye dashes, flat sleeping mouth. Body horizontal, blanket lines. The dream bubble: navy fill with white shapes inside — a small white running stick figure, a white spiral, a white question mark. The overall effect is a dark, inward dream world. Text: "HOUR 68: DREAMING IS JUST INNER DARK." Flat colour, MS Paint doodle style.

PROMPT 85 [2:48–2:50]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman waking up — sitting up in bed, mid-sit-up motion. The stickman: medium circle head raised upright (staring straight ahead), dot eyes very wide (sudden waking — large filled black circles, wide open), a small O-shaped surprised mouth. Body partially upright (body line at 45 degrees — halfway between lying and sitting). Right arm pressed flat on the bed for support. Left arm hanging slightly. Legs still under the blanket. Around the head: four exclamation marks floating in the white space. A speech bubble: "WHAT TIME IS IT?!" Text at top: "HOUR 70: AWAKE AGAIN." Flat colour, MS Paint doodle style.

PROMPT 86 [2:50–2:52]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. An infographic with a body outline (simplified stickman body: circle head, box torso, stick arms and legs). Different zones of the body are marked with status labels. HEAD (brain region): red zone, labelled "CONFUSED." CHEST/HEART region: yellow zone, labelled "ELEVATED RATE." STOMACH region: orange zone, labelled "IRREGULAR HUNGER." ARMS/LEGS region: grey zone, labelled "FATIGUED." The body is divided into coloured zones like a map. All zones connect to labels with thin lines. Text at the top: "YOUR BODY AT HOUR 72." Flat colour, MS Paint doodle style.

PROMPT 87 [2:52–2:54]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman seeing their first hallucination. The stickman: medium circle head, dot eyes extremely wide (the widest they've been — large filled circles taking up most of the head), a strongly open O-shaped mouth (stunned gasping). Both arms raised to face level — hands covering the lower face in shock (arms bent upward, sticks pressed to the lower head circle area). Legs stumbling backward (left leg back, right leg forward, both slightly bent — stumbling). In front of the stickman, floating in the white space: a ghostly apparition — a slightly-transparent circle and line stickman shape (identical to the viewer's stickman but drawn in light grey dotted lines — a ghost image). Below it: "IS THAT REAL?" Flat colour, MS Paint doodle style.

PROMPT 88 [2:54–2:56]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A bold graphic statement frame. Centre: a thick border box (double rectangle outline). Inside the box, bold black hand-lettered text in all caps: "THIS IS THE BRAIN WITHOUT A COMPASS." Beneath this text inside the box: a small illustration of a compass — a circle with N, S, E, W marked, and the compass needle — but the needle is spinning (indicated by multiple needle positions drawn in different angles with motion lines). No stickman. Clean, bold, impactful single statement frame. Flat colour, MS Paint doodle style.

"""

with open('/home/user/OG-youtube/264_image_prompts.txt', 'a') as f:
    f.write(content)
print("Part 2 appended: Prompts 45-88")
