content = """THE ANCIENT BRAIN — "What Happens to the Human Brain During Total Darkness"
264 IMAGE PROMPTS AT 2-SECOND INTERVALS (Total Runtime: 529 seconds)
Visual Style: Hand-drawn 2D stick-figure / MS Paint doodle aesthetic
All human characters: STRICTLY stickman (circle head, line body, stick arms, stick legs)
Colour palette: White, black, flat yellow, flat navy blue, flat red accents

══════════════════════════════════════════════════════════
SECTION 1: HOOK & OPENING (Prompts 1–30 | 0:00–1:00)
══════════════════════════════════════════════════════════

PROMPT 1 [0:00–0:02]
Hand-drawn 2D stick-figure / MS Paint doodle style. Pure flat black background — no other elements. A single thin white horizontal hairline stroke sits at the dead centre of the frame, barely visible, like a horizon swallowed by dark. No figures, no text, no objects. The entire frame is a flat black rectangle drawn in MS Paint. The hairline is one pixel thick and suggests infinite emptiness. No gradients, no shading, no glow effects.

PROMPT 2 [0:02–0:04]
Hand-drawn 2D stick-figure / MS Paint doodle style. Full flat black background. A single stickman figure rendered as a ghostly white outline against the black — the only visible element in the frame. The stickman has a medium circle head (wide diameter, thin white outline only, not filled), two pin-dot eyes drawn as tiny filled white circles (wide apart, enlarged with fear), and a thin horizontal straight-line mouth pressed tight with tension. The body is one vertical white line running from chin to below the head. Two stick arms hang perfectly straight down at the sides of the body — no angle, no bend. Two stick legs stand together with feet nearly touching. The figure is centred in the frame, small relative to the overall black field, completely alone and isolated. No text, no labels.

PROMPT 3 [0:04–0:06]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. Bold black hand-lettered text dominates the upper half of the frame: "WHAT HAPPENS TO" on the first line, then "THE HUMAN BRAIN" on the second line in slightly larger uneven letters, then "IN TOTAL DARKNESS" on a third line, the largest of the three. The text has slightly wobbly edges suggesting hand-drawn marker strokes. Below the text block, a small stickman stands centred: medium circle head (clean circle outline, white fill), two wide-open dot eyes (two small filled black circles, placed centre of head), a small open-circle mouth (slightly round — a small 'O' shape suggesting awe or nervousness). Single vertical body line. Both arms raised outward at 45 degrees from the body. Legs standing apart at shoulder width. Black outlines throughout. Flat colour only.

PROMPT 4 [0:06–0:08]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A single stickman stands left of centre: medium circle head (smooth circle, white fill, thick black outline), two small neutral dot eyes (small filled black circles, evenly spaced), a straight horizontal line mouth (no expression — neutral). Single vertical body line. The LEFT arm is raised and extended upward at a 45-degree angle with the index finger pointing upward (the arm stick ends in a small circle for the hand, with one tiny line extending up as the pointing finger). The RIGHT arm hangs straight at the side. Both legs stand together, feet touching. To the upper right of the figure, a large speech bubble — a white oval with a pointed tail connecting to the mouth area — contains the bold black text: "IMAGINE THIS." The speech bubble has a clean black outline. MS Paint style, black on white.

PROMPT 5 [0:08–0:10]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A simple rectangular room outline drawn in thick black lines — four walls visible as a thin rectangle framing the scene, with a small rectangular door shape on the right wall and a small square window on the left wall. Inside the room, centred: a stickman standing comfortably. The stickman has a medium circle head (circle outline, white fill), two half-circle-shaped dot eyes suggesting a relaxed expression (two small black dots with a tiny curved line above each — eyebrows slightly raised, alert but calm), and a very slight upward curve for a mouth (gently satisfied). Single vertical body. Both arms hang loosely at 45 degrees from the body sides. Legs standing apart in a relaxed stance. Above the stickman, fixed to the ceiling (top wall line), a simple circular light fixture: a circle with four short radiating lines around it (a sun-like lamp symbol) in yellow with black outline. Flat colour, no gradients.

PROMPT 6 [0:10–0:12]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. Same rectangular room outline as before. The square window on the left wall now has a thick navy blue rectangle drawn across it — a flat-colour curtain shape (straight edges, navy fill, black outline). The overhead light circle now has a large black X drawn through it (light switched off). The corners of the room have begun to fill in with a soft navy blue — drawn as navy triangles in the four corners of the rectangle, suggesting encroaching darkness. The stickman inside: medium circle head (circle outline, white fill), dot eyes now slightly larger and more alert (two slightly larger filled black dots, wider apart), a straight horizontal mouth (uncertain, neutral). Both arms hanging at sides, legs together, body upright but slightly rigid. The navy fills are flat, no gradient.

PROMPT 7 [0:12–0:14]
Hand-drawn 2D stick-figure / MS Paint doodle style. The frame is 80% covered in flat navy blue fill — the dark has expanded to almost the entire frame. A small white area remains in the bottom-right corner. The stickman is positioned mostly within the navy area, visible only as a white outline against the dark. The stickman: medium circle head (white circle outline only against navy), eyes now VERY large and wide — two large filled white circles (the whites of the eyes), with a tiny black pupil dot in the centre of each (classic horror/fear eye). A wavy zigzag line mouth — distressed, trembling. The body line is white. Left arm raised at 90 degrees beside the head. Right arm raised at 90 degrees on the other side — both arms up in an alarmed, bracing gesture. Legs bent slightly at the knee, feet apart — the figure is stepping backward. No text. Flat navy and white only.

PROMPT 8 [0:14–0:16]
Hand-drawn 2D stick-figure / MS Paint doodle style. Full flat navy-black background — the entire frame is dark. Only two elements are visible: two medium-sized white circle shapes floating in the navy dark at head height, positioned where a face would be — representing the whites of two eyes. Each white circle contains a tiny filled black pupil dot (very small relative to the circle — suggesting dilation in the dark). Below the eye circles, a tiny thin curved-down line (a frown in the dark). Everything else is invisible navy. No body, no arms, no labels visible. The viewer sees only floating terrified eyes in blackness. MS Paint doodle aesthetic, flat white on navy.

PROMPT 9 [0:16–0:18]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A single enormous question mark dominates 70% of the frame — drawn in thick, slightly wobbly black strokes (MS Paint hand-drawn quality). The curved upper body of the question mark is extra thick, the dot at the bottom is a large filled circle. Peeking from the inside of the curled top of the question mark, a tiny stickman appears to be trapped or emerging. The tiny stickman: very small circle head (proportionally small), two wide dot eyes (proportionally large — frightened), a downturned curved line mouth. One tiny stick arm reaches outward through the curve of the question mark as if pushing against it. The other arm is hidden behind the curve. Tiny stick legs visible at the bottom of the symbol. Bold black text below the question mark: "THREE DAYS. NO LIGHT." Text in all caps, slightly uneven letter heights suggesting hand lettering. Flat black on white.

PROMPT 10 [0:18–0:20]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A two-panel infographic divided by a thick black horizontal centre line. TOP PANEL labelled "WITH LIGHT" in small black caps at the top left: a simple yellow sun shape (circle with six radiating lines) sits in the upper right corner. A stickman stands relaxed at centre — medium circle head, two half-moon shaped eyes (curved upward, relaxed), a gentle upward-curve mouth (content), body upright, arms hanging loosely at 20 degrees from body, legs shoulder-width apart in easy stance. BOTTOM PANEL labelled "WITHOUT LIGHT": same dimensions, but the upper corner is solid navy. The stickman in this panel: same medium circle head, but eyes wide and circular (fearful), a downturned curved line mouth (distressed), body line slightly curved (hunched), arms crossed over the chest (both stick arms crossing the body line at mid-torso). Legs pressed together. Flat colour, MS Paint style.

PROMPT 11 [0:20–0:22]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A horizontal timeline arrow stretching across the bottom third of the frame, left to right. Three tick marks on the line labelled "HOUR 6," "DAY 2," and "DAY 3" respectively. Above each tick mark, a small stickman figure showing progressive deterioration. HOUR 6 STICKMAN: small proportions — small circle head, normal dot eyes, straight mouth, arms at sides, legs together, standing tall. DAY 2 STICKMAN: slightly larger circle head tilted 10 degrees sideways, one arm raised to the head (arm bent, stick touching the side of the head circle), eyes slightly wider, mouth a flat uncertain line, legs slightly apart. DAY 3 STICKMAN: medium circle head tilted further, BOTH arms raised upward and outward in alarm, very wide dot eyes, strongly downturned curved line mouth, legs spread wide apart in unsteady stance. Three stickmen all slightly different sizes for visual separation. Flat colour, MS Paint style.

PROMPT 12 [0:22–0:24]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A single large brain shape dominates the centre of the frame — drawn as an irregular oval with six squiggly fold lines across the top surface (classic cartoon brain), filled with flat yellow colour and outlined in thick black. From the brain, three thick black arrows point outward in different directions: an arrow pointing straight UP labelled "THOUGHTS" in black caps. An arrow pointing LEFT labelled "EMOTIONS." An arrow pointing DOWN labelled "TIME SENSE." All labels are in hand-drawn black caps slightly uneven. The brain itself has no face or expression — it is the subject of the diagram. No stickman in this frame. Clean flat yellow on white. MS Paint doodle style.

PROMPT 13 [0:24–0:26]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman in mid-stride walking pose occupies the left two-thirds of the frame: medium circle head, two forward-looking dot eyes (both dots slightly toward the right side of the head — looking ahead), a neutral straight-line mouth. Single vertical body. Right arm swung forward (arm stick extended forward at 30 degrees), left arm swung back (arm stick extended backward at 30 degrees) — walking motion. Right leg forward (angled), left leg behind (angled) — mid-stride. To the right of the walking figure, occupying the right third of the frame: a solid navy rectangle with bold white text inside reading "NO LIGHT." The stickman is clearly walking toward this dark zone. A large bold arrow between the stickman and the rectangle points rightward. Text at the top of the frame in black caps: "THREE SCIENTISTS DID THIS." Flat colour, MS Paint doodle style.

PROMPT 14 [0:26–0:28]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. Centre frame: a large analogue clock face drawn with a thick black irregular circle outline (slightly wobbly, hand-drawn feel). Clock face is white with twelve short tick marks around the inside edge. Two bold clock hands both pointing to 12 — both at the top. Around the clock face, five red X marks are drawn at various hour positions (1 o'clock, 3 o'clock, 6 o'clock, 9 o'clock, and 11 o'clock positions) — each X is bold red, slightly rotated and rough. The X marks suggest those hours are being eliminated or lost. Below the clock, in bold black hand-lettered caps: "YOUR BRAIN LOST COUNT." No stickman. Flat colour, MS Paint style.

PROMPT 15 [0:28–0:30]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A single stickman stands at centre in a thinking pose: medium circle head (circle outline, white fill), dot eyes directed upward-left (both dots positioned in the upper-left area of the head circle — classic thinking direction), a small rounded open-circle mouth shape (pondering, slightly open). Body upright. LEFT arm bent at 90 degrees with the stick ending near the bottom of the chin area (hand on chin thinking gesture). RIGHT arm hangs loosely at the side. Legs together, feet touching. A classic thought bubble extends from the upper-left of the head: three progressively larger circles (small to medium to large), leading to a cloud-shaped final bubble. Inside the cloud bubble: a small crescent moon, three tiny star asterisk marks, and a single question mark symbol. Black outlines on white, flat colour, MS Paint doodle style.

PROMPT 16 [0:30–0:32]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A two-panel comparison. LEFT PANEL: a simple bed drawn as a horizontal rectangle with a small pillow bump at the left end and three horizontal lines across it suggesting a blanket. A stickman lies in the bed: small circle head tilted (lying on side), two horizontal line marks for closed eyes (two short flat dashes — peaceful sleep), a small gently curved upward line for mouth (sleeping peacefully). Body line horizontal along the length of the bed. Arms tucked along body sides. Legs extended straight. A small yellow crescent moon in the upper left corner of the panel. RIGHT PANEL: identical bed, identical stickman sleeping position, but the crescent moon is replaced by solid flat navy fill in the upper right corner — darkness instead of gentle night light. The sleeping stickman in the right panel has an expression shift: the closed-eye marks now have slight downward curves (furrowed brow in sleep), the mouth is a flat tight line. Text below each panel: "NORMAL NIGHT" and "TOTAL DARK." MS Paint doodle style.

PROMPT 17 [0:32–0:34]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A large circle occupying most of the frame — representing a cross-section view of a human head. Thick black circle outline, white fill. Two small ear bumps on either side (simple half-circle bumps on the circle outline at ear-height). Inside the circle, a lumpy yellow oval shape represents the brain — positioned in the upper portion of the head circle. The brain oval has three squiggly fold lines. Inside the brain, toward the lower centre: a tiny square labelled "SCN" in small caps, with a four-pointed star glow symbol drawn around it in yellow (suggesting it is lit/active). Two simple dot eyes visible below the brain, near the equator of the head circle. Bold text just outside the head circle at the top: "MASTER CLOCK." An arrow points from this text to the SCN square. No stickman body — just the head cross-section. Flat yellow on white, MS Paint style.

PROMPT 18 [0:34–0:36]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A large simplified eye illustration dominates centre frame: an oval outline (the eye shape), a circle inside (the iris), a smaller filled circle inside the iris (the pupil). The iris is flat blue fill. From the LEFT of the eye (external side): a bold arrow points rightward INTO the pupil, labelled "LIGHT IN" with a small yellow star burst at the arrow tip. From the RIGHT of the eye (toward the brain side): a dotted bold arrow points further rightward, labelled "→ SCN SIGNAL." The dotted arrow terminates at a small brain shape (oval with fold lines) in the far right of the frame, labelled "SCN" with a small yellow glow. The eye is drawn with thick black outlines, flat colour. No stickman. MS Paint doodle style, flat colour.

PROMPT 19 [0:36–0:38]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A profile/side-view head silhouette: a rounded oval drawn from the side showing the forehead curve, nose bump, mouth area, and chin. The outline is thick black. Inside the head outline, visible brain anatomy in simplified cartoon form: a lumpy brain oval (yellow) fills the upper portion. In the lower-centre of the brain shape, a small bright yellow-orange star burst shape glows — this is the SCN. An arrow from outside the head profile points to the star burst, with the label "SCN" and beneath it "HYPOTHALAMUS" in smaller text. A small circle represents the eye on the visible side of the profile, with a thin dotted line connecting the eye to the SCN star burst (the optic pathway). Flat colour, MS Paint doodle style. No full stickman.

PROMPT 20 [0:38–0:40]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. Centre frame: a brain shape (irregular oval, yellow fill, thick black fold lines on top, black outline). Inside the brain, TWO small orange-yellow star burst shapes positioned symmetrically — one on the left side, one on the right side (the paired SCN nuclei). Each star burst has three radiating lines in orange. A bracket points to both stars simultaneously with the label "20,000 NEURONS" in bold black caps. Below the brain shape, centred: "YOUR BODY'S PACEMAKER" in smaller black caps. The brain outline is clean and slightly wobbly (hand-drawn feel). No stickman. Flat yellow and orange on white background. MS Paint doodle style.

PROMPT 21 [0:40–0:42]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. Centre frame: a large alarm clock — circular face with two bell domes on top, a rectangular base/feet at the bottom, drawn in bold thick black lines. The clock face is yellow fill. Clock hands point to 6:00 AM. Around the outside of the clock face, twelve short tick marks for hours. From the clock, four radiating lines extend outward in cardinal directions — yellow lines suggesting a glow or alarm (the ringing/light association). Below the clock, a thick black downward arrow leads to a small horizontal rectangle (a simple bed silhouette). Beside the arrow: "WAKE SIGNAL" in black caps. The alarm bells on top are slightly vibrating — indicated by three short curved lines on either side of each bell. Flat colour, MS Paint doodle style.

PROMPT 22 [0:42–0:44]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. LEFT THIRD of frame: a bold yellow sun — circle with six radiating lines. RIGHT THIRD of frame: a flat navy crescent moon shape. CENTRE THIRD: a stickman standing upright between the two symbols. The stickman: medium circle head (circle outline, white fill), two dot eyes (two filled black circles, neutral gaze looking straight ahead — forward-facing), a straight horizontal line mouth (neutral). Single vertical body line. Both arms hang at 20 degrees from the body. Legs standing apart at shoulder width. Two bold black arrows originate from the stickman's head: one pointing LEFT toward the sun, labelled "AWAKE." One pointing RIGHT toward the moon, labelled "SLEEP." The arrows are thick with arrowheads. Flat colour throughout, MS Paint doodle style.

PROMPT 23 [0:44–0:46]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A large circle (24-hour clock face) dominates most of the frame. The LEFT semicircle is filled with flat yellow (daytime). The RIGHT semicircle is filled with flat navy (nighttime). Around the circumference: twenty-four short tick marks, evenly spaced. "12" labels at the top and bottom (noon and midnight). A single thick black clock hand extends from the centre, pointing to approximately the 8 o'clock position on the circle (8 AM in the yellow daytime section). Inside the yellow half: a tiny stickman figure — very small proportions — standing upright: small circle head, tiny open dot eyes, arms at sides, legs together. Inside the navy half: same tiny stickman but horizontal (lying down sleeping): horizontal body line, closed-eye marks, arms at sides. Flat colour, MS Paint doodle style.

PROMPT 24 [0:46–0:48]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A simple vertical flowchart with four boxes connected by downward arrows. BOX 1 (top): yellow rectangle, black outline, text inside: "LIGHT ENTERS EYES." BOX 2: yellow rectangle, text: "SCN RECEIVES SIGNAL." BOX 3: yellow rectangle, text: "HORMONES ADJUST." BOX 4 (bottom): green-outlined rectangle (only the outline is green, white fill), text: "BODY CLOCK RESETS ✓." All boxes have slightly uneven rounded corners (hand-drawn feel). Connecting arrows between each box are thick black with pointed arrowheads. Text inside all boxes is in black caps, slightly varying in size (hand-lettered feel). No stickman. Flat colour, black, yellow, and green on white. MS Paint doodle style.

PROMPT 25 [0:48–0:50]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman stands left of centre facing right: medium circle head, two dot eyes directed to the right (both dots positioned toward the right side of the head circle), a slight upward curve of the mouth (curious, alert). Single vertical body. Left arm raised, pointing rightward at a 45-degree angle (extended toward the dark zone on the right). Right arm hangs at side. Legs apart, weight slightly forward on right leg (leaning toward subject of interest). To the right of the stickman: a solid navy rectangle occupying the right third of the frame, with bold white hand-lettered text inside: "NO LIGHT." Between the stickman and the rectangle: a large bold red question mark. At the top of the frame: "WHAT HAPPENS WHEN..." in black caps. Flat colour, MS Paint doodle style.

PROMPT 26 [0:50–0:52]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. Centre frame: a large hourglass shape — two triangles meeting at the narrow centre, with rounded outer edges drawn in thick black lines. The TOP bulb is nearly empty — just a thin navy layer at the very bottom of the top section, suggesting sand almost gone. The BOTTOM bulb is filled completely solid navy. The narrow neck between the bulbs has a few tiny dots flowing through it. Surrounding the hourglass: three small stickman figures, one on the left, one on the right, one below. Each stickman: small proportions — small circle head with two dot eyes directed AT the hourglass (eyes turned inward toward the hourglass), small open-circle mouths (surprised). Arms slightly raised at sides (gestural alarm). Legs apart, stable stance. Text above the hourglass: "YOUR INTERNAL CLOCK." Flat navy and white, MS Paint doodle style.

PROMPT 27 [0:52–0:54]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A long horizontal bar stretching across the width of the frame, divided into 24 equal segments (one per hour). The first 8 segments are filled flat yellow (morning/day hours). The next 8 segments are filled flat light grey (afternoon). The final 8 segments are filled flat navy (night). Below the right edge of the bar (at the transition from grey to navy), a small stickman stands directly under the dividing line: medium circle head, two dot eyes directed upward toward the bar, right arm raised pointing at the division point, left arm at side. Legs together, standing. Text above the bar: "THE 24-HOUR RHYTHM." At the left end of the bar: "DAWN." At the right end: "MIDNIGHT." All text in black caps. MS Paint doodle style, flat colour.

PROMPT 28 [0:54–0:56]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. Centre frame: a light bulb shape — a round glass dome on top with a threaded rectangular base below, drawn in thick black outlines. Inside the dome: three short radiating lines (the lit filament). The dome has a flat yellow fill (illuminated). Overlaid ON TOP of the light bulb: a solid flat navy rectangle (larger than the bulb) covering it completely — like a blackout blind placed over it. The navy rectangle has a red arrow pointing to it from the right: "REMOVE THIS." To the left of the covered bulb: a stickman — medium circle head with dot eyes directed at the covered bulb, eyebrows drawn as two short angled lines above the eyes (furrowed, concerned), straight-line mouth. Right arm extends toward the bulb, pointing. Left arm at side. Legs apart, stable. MS Paint doodle style, flat colour.

PROMPT 29 [0:56–0:58]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A body diagram: a stickman but with the internal systems visible. A medium circle head (circle outline) with inside the head circle, a small lumpy brain shape (yellow). Below the head, a single body line. A rectangular torso outlined in thin black lines surrounds the body line (a simple box torso). Inside the torso box: a small clock icon — a circle with two clock hands pointing to roughly 10:10 position. A dotted line connects the brain shape inside the head to the clock shape inside the torso. Two stick arms extend from the torso box sides. Two stick legs below. Text label outside, with a line pointing to the clock: "INTERNAL CLOCK." Text label pointing to the brain: "MASTER CONTROLLER." Both labels in black caps. Flat colour, MS Paint doodle style.

PROMPT 30 [0:58–1:00]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A before/after side-by-side comparison. LEFT PANEL labelled "WITH LIGHT" at the top: a small yellow sun (circle with radiating lines) in the upper corner. A stickman stands confidently: medium circle head, two gently upward-curved eye marks (smiling eyes — arched upward, like ^^), a clear upward-curved line mouth (happy), body upright and straight, both arms slightly raised at 30 degrees from the body sides (confident, open posture), legs apart in a stable balanced stance. RIGHT PANEL labelled "WITHOUT LIGHT" at the top: upper corner solid navy. Same-proportioned stickman: medium circle head, eyes now large filled dots (slightly wider, worried), a straight flat line mouth (uncertain), body line slightly curved (hunched), one arm raised to forehead in a confused/questioning gesture (bent at elbow, stick pressing to the head circle), the other arm hanging loosely. Legs slightly closer together, less stable stance. Flat colour, MS Paint doodle style.

══════════════════════════════════════════════════════════
SECTION 2: CIRCADIAN CLOCK DEEP DIVE (Prompts 31–60 | 1:00–2:00)
══════════════════════════════════════════════════════════

PROMPT 31 [1:00–1:02]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman stands at centre gazing at their own raised left wrist: medium circle head, two dot eyes directed sharply downward-left toward the wrist area, a small neutral straight-line mouth. Single vertical body. LEFT arm bent at 90 degrees at the elbow, the lower forearm stick raised horizontally — a small square watch icon drawn on the wrist stick (a tiny square outline with a circle clock face inside and two tiny hands). RIGHT arm hangs straight at the side. Legs together, feet touching. A thought bubble extends from the upper right of the head: three small circles leading to a cloud shape containing a single large question mark. Below the figure: "HOUR ONE." in bold black caps. Flat colour, MS Paint doodle style.

PROMPT 32 [1:02–1:04]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A simple graph fills the frame: a horizontal axis labelled "TIME →" and a vertical axis labelled "MELATONIN LEVEL ↑." The graph line is a thick black curve: it starts low on the left (daytime — low melatonin), then rises steeply at approximately two-thirds along the axis, but a bold red arrow points to the upswing with the note "TOO EARLY" in red caps beside it. The peak of the curve is circled in a red oval. A small vertical dotted line marks where the peak SHOULD be (correct time) — positioned to the right of where the early peak occurs. The correct marker is labelled "SHOULD BE HERE" in small black text. No stickman. Flat colour, black and red on white. MS Paint doodle style.

PROMPT 33 [1:04–1:06]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. TOP of frame: a yellow brain shape (oval with fold lines, thick black outline). From the bottom of the brain, a thick dotted vertical arrow points DOWNWARD. At the bottom of the arrow: a small alarm clock shape (circle face with two bells on top, vibration lines on both sides indicating ringing). The alarm clock face shows 3:00 PM — the wrong time for melatonin. The clock face has two small X marks for eyes and a downturned arc for a mouth (the clock itself looks distressed). A speech bubble from the brain reading: "MELATONIN — NOW!" A bold red X below the alarm clock with the text "WRONG TIME." Flat colour, MS Paint doodle style.

PROMPT 34 [1:06–1:08]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman lies in a simple bed — a horizontal rectangle with a small pillow bump at the left end and three horizontal lines suggesting a blanket over the lower body. The stickman: medium circle head tilted to one side (resting on the pillow), two half-open eye marks (small dots with a tiny semi-circle arc above each dot — droopy, drowsy lids), a small horizontal straight-line mouth (drowsy neutral). Body line is horizontal along the length of the bed. Both arms along the body at the sides. Legs extended straight under the blanket. In the upper right corner of the frame: a crescent moon shape, but beside it a bold question mark (the timing of this sleep feels wrong). At the top of the frame in black caps: "MELATONIN SURGE — HOUR 6." Flat colour, navy moon, white background, MS Paint doodle style.

PROMPT 35 [1:08–1:10]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A large thermometer at centre frame: a tall thin rectangle with a round bulb at the bottom. The mercury column inside is a red fill rising only halfway up the thermometer (temperature reading low). A bold downward black arrow runs alongside the thermometer with the label "CORE TEMP ↓" in red caps beside it. To the right of the thermometer: a stickman standing and appearing cold. The stickman: medium circle head, two dot eyes (slightly squinted — cold squint, dots with small curved lines below as if wincing), a wavy zigzag line mouth (shivering), single vertical body, both arms crossed in front of the body (both stick arms drawn crossing the body line at mid-chest height, suggesting hugging oneself for warmth), legs together, pressed tight. Text at top: "BODY TEMPERATURE DROPPING." Flat colour, red, black on white, MS Paint doodle style.

PROMPT 36 [1:10–1:12]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman lies in bed, clearly NOT sleeping. The bed: horizontal rectangle, pillow bump on left, blanket lines. The stickman: medium circle head tilted on pillow, eyes WIDE OPEN — two large filled dot circles (not the resting half-closed marks, but the fully open, alert dots), a wavy horizontal line for mouth (restless, uneasy). Both arms bent upward, behind the head — sticks raised to head height, elbows outward (the classic awake-in-bed hands-behind-head pose). Legs slightly bent (restless leg movement suggested). Above the stickman's head: a large spiral shape (four concentric irregular circles spiralling inward — representing spinning anxious thoughts). Text at the top: "HOUR 8: SLEEP WON'T COME." A small crescent moon in the upper corner crossed out with a red X. Flat colour, MS Paint doodle style.

PROMPT 37 [1:12–1:14]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. Two side-by-side panels. LEFT PANEL labelled "NORMAL SLEEP" at top: a wavy sine wave drawn in navy blue — three smooth regular peaks and troughs representing normal sleep cycle waves. The wave is clean and even. RIGHT PANEL labelled "DARKNESS SLEEP" at top: the same scale wave but now jagged, irregular, and erratic — drawn in red. Some peaks are very high, some troughs very deep, some segments are flat, some are spiked. A key SPIKE on the red line is circled in red. No stickman. Clean infographic. The two waves fill the lower two-thirds of each panel. Flat colour, MS Paint doodle style.

PROMPT 38 [1:14–1:16]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A horizontal arrow timeline bar stretching across the full width of the frame. Four tick marks with labels: "HOUR 1," "HOUR 6," "HOUR 12," "HOUR 24." Above each tick mark, a simple status icon. Above HOUR 1: a small yellow sun with six lines (sunny, okay). Above HOUR 6: a yellow half-circle sun (half gone). Above HOUR 12: a navy crescent moon (night hormones flooding). Above HOUR 24: a solid navy filled circle with a bold red X overlaid on it (system in distress). All icons drawn flat colour, simple shapes. No stickman. Bold arrow on the timeline pointing rightward. MS Paint doodle style.

PROMPT 39 [1:16–1:18]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman stands in the centre of the frame, appearing disoriented. The stickman: medium circle head, two dot eyes misaligned (left eye dot positioned slightly HIGHER than the right eye dot, and one dot aimed slightly left while the other aims slightly right — a disoriented crossed look), a wavy horizontal mouth line (nausea/confusion). Single vertical body line drawn at approximately 8 degrees off vertical (tilted) — the whole figure is leaning. Both arms extended outward at 90 degrees to the body sides (arms spread wide for balance). Legs apart, feet pointing slightly outward in an unsteady stance. Around the head: three filled black question marks floating at head height (one left, one right, one above). Text below the figure: "WHAT TIME IS IT?" in bold black caps. Flat colour, MS Paint doodle style.

PROMPT 40 [1:18–1:20]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A simple wall scene: a horizontal black line represents a wall/shelf near the top of the frame. Hanging from the wall (attached by two short lines): an analogue clock — round face, two bells on top, clock hands pointing to an unusual time (3:47). The clock face is white with a black outline. A stickman stands below, reaching both arms upward toward the clock: medium circle head, two dot eyes directed upward (dots in the upper portion of the head circle), an open round O-shaped mouth (surprise, alarm). Single body line. Both arms raised upward at 60 degrees, stick fingertips pointing toward the clock. Legs apart, weight slightly on toes (reaching up). Beside the clock hands: a small red X. Text at the top: "HOUR 12: THE CLOCK FEELS WRONG." Flat colour, MS Paint doodle style.

PROMPT 41 [1:20–1:22]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. Two stickman figures standing side by side with space between them. LEFT FIGURE labelled "YOU" beneath: medium circle head, two dot eyes directed slightly rightward (looking at the other figure), a half-closed eye expression with a slight downward mouth (tired, uncertain). Body upright. Arms loosely at sides. Legs standing. RIGHT FIGURE labelled "YOUR BRAIN" beneath: same proportioned stickman, but the head circle has six squiggly brain fold lines drawn ON the OUTSIDE SURFACE of the head circle (indicating it IS the brain). The brain-head figure has two dot eyes directed slightly leftward (looking back at "YOU"). Expression: slightly suspicious sideways look. Between the two figures: a thick double-headed arrow (pointing both left and right) with a large question mark drawn ON the arrow shaft. Text above: "HOUR 18: WHO'S IN CHARGE?" Flat colour, MS Paint doodle style.

PROMPT 42 [1:22–1:24]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. Centre: a large warning/hazard triangle — equilateral triangle, thick black outline, bright yellow fill. Inside the triangle: a brain shape (small lumpy oval in the centre of the triangle) with a lightning bolt shape inside the brain (a bold zigzag line). Text beneath the triangle in bold black caps: "CORTISOL SPIKE." On either side of the warning triangle, two small stickman figures reacting. LEFT STICKMAN: small circle head, two very wide dot eyes (large and round — alarmed), both arms raised above the head (arms bent upward at shoulder height, hands raised — an "oh no!" pose), legs bent at the knee (startled). RIGHT STICKMAN: small circle head, one arm raised to the side of the face (shielding or covering), the other arm raised defensively in front of chest, legs apart. Both faces show alarm. Flat colour, yellow and black on white. MS Paint doodle style.

PROMPT 43 [1:24–1:26]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman stands centre frame in a neutral but tired stance: medium circle head, two dot eyes (slightly lower in the head circle — drooping, fatigued), a perfectly straight horizontal line for mouth (blank fatigue). Single vertical body. RIGHT arm extended forward, holding a simple tall rectangle shape (a glass of water — the rectangle is white with a blue outline and a small wavy line inside suggesting water level). LEFT arm hangs straight at side. Legs apart in a standing pose, slightly wider than shoulder width (grounded). Below the stickman, slightly right of centre: a simplified kidney shape outline (labelled "KIDNEYS" in small black text), with a small red downward arrow beside it and the label "DEHYDRATION" in red. Text at the top: "HOUR 20." Flat colour, MS Paint doodle style.

PROMPT 44 [1:26–1:28]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A horizontal row of FIVE stickman figures across the frame — same figure at five stages of deterioration. Beneath each: the labels "H6," "H12," "H18," "H24," "H30." FIGURE H6: medium circle head, dot eyes open and level, straight-line mouth, body straight vertical, arms hanging loosely at sides, legs apart and stable. FIGURE H12: medium circle head, dot eyes slightly wider and lower, straight mouth, body vertical but arms one raised slightly to head (questioning gesture). FIGURE H18: medium circle head tilted 10 degrees, dot eyes larger (worried), downturned mouth curve, body tilted slightly, one arm raised to head, one arm out for balance. FIGURE H24: medium circle head tilted 15 degrees, very wide dot eyes, strongly downturned mouth, body curved and bent, one arm out far for balance, legs uneven. FIGURE H30: medium circle head severely tilted, closed-squint eyes (two short dashes), open distressed mouth curve, body heavily curved, both arms out wide, legs splayed. Flat colour, MS Paint doodle style.

"""

with open('/home/user/OG-youtube/264_image_prompts.txt', 'w') as f:
    f.write(content)
print("Part 1 written: Prompts 1-44")
