content = """
══════════════════════════════════════════════════════════
SECTION 4: MICHEL SIFFRE — 1962 CAVE EXPERIMENT (Prompts 89–132 | 2:56–4:24)
══════════════════════════════════════════════════════════

PROMPT 89 [2:56–2:58]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A bold title card. Centre of frame: a thick black outlined rectangle. Inside: "MICHEL SIFFRE" in large bold hand-lettered black caps, with "FRANCE, 1962" below it in smaller caps. Below the name, a simple small stickman figure: small circle head, dot eyes looking straight forward (alert, brave), a slight upward curve of mouth (confident). Body upright. Both arms at sides. Legs together. The stickman stands under the name text like a portrait subject. Flat colour, MS Paint doodle style.

PROMPT 90 [2:58–3:00]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman in explorer gear — though still strictly a stickman, indicated by accessories: on the head circle, a small circle drawn on top (a helmet/hard hat shape — a circle on top of the head circle with a small brim line). A rope coil drawn as a circle of rope hanging from the right arm stick. A small backpack rectangle drawn behind the body line. The stickman: medium circle head with the helmet, dot eyes directed forward (adventurous, focused), a straight confident line for mouth. Body upright. Left arm at side. Right arm with rope coil. Legs in mid-stride (left leg forward, right leg back). Text: "A GEOLOGIST AND SPELEOLOGIST." Flat colour, MS Paint doodle style.

PROMPT 91 [3:00–3:02]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A simple map of France and the Alps — very rough and doodle-like. France is drawn as an irregular polygon outline. A mountain triangle shape in the lower right of France outline represents the Alps (three overlapping triangles of varying heights). A bold X marks the spot on the mountain. An arrow from outside France points to the X with text: "SCARASSON CAVE, FRENCH ALPS." The map has no detail — just the rough coastline and borders, hand-drawn. No stickman. Flat colour, MS Paint doodle style.

PROMPT 92 [3:02–3:04]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A cross-section illustration of the Earth's surface and a cave below. The surface: a horizontal wavy line across the upper portion of the frame, with three simple triangle mountains on it. Below the surface line: a cross-section of rock (indicated by irregular grey-ish hatching lines in flat grey). Within the rock: a hollow irregular cave shape — a blob outline with no fill (white interior). Inside the cave: a tiny stickman (very small proportioned to show depth). The tiny stickman: small circle head, dot eyes, arms at sides, legs together. Text beside the cave: "130 METRES UNDERGROUND." An arrow with a measurement line shows the depth from surface to cave. Flat colour, MS Paint doodle style.

PROMPT 93 [3:04–3:06]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman descending a rope into a cave opening. The cave opening: a large oval hole in the ground (the ground is a horizontal line, the cave entrance is a dark navy oval below it). The stickman is mid-rappel on the rope: medium circle head tilted slightly (looking down), dot eyes directed downward, neutral set mouth (concentration). Body at roughly 45 degrees (leaning back on the rope). Both hands gripping the rope (both sticks raised, gripping an imaginary rope — the rope is a thick vertical line running from off-frame top down into the navy cave oval). Legs slightly bent at the knee, feet touching the cave wall. Text: "ALONE. NO CLOCK. NO CALENDAR." Flat colour, MS Paint doodle style.

PROMPT 94 [3:06–3:08]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. Interior of the cave — indicated by an irregular oval outline filling most of the frame (the cave walls), with a navy blue fill around the inside edges of the oval, leaving a white centre. Inside the white centre of the cave: a stickman standing with basic camping equipment. A small tent shape beside them (triangle with a floor line). A lantern icon (a rectangle with vertical lines inside) on a flat surface. The stickman: medium circle head, dot eyes looking around (one eye directed left, one directed right — surveying), a neutral mouth. Body upright. Both arms slightly raised at sides (taking in the space). Legs apart. Text inside the cave wall area: "TWO MONTHS. ALONE." Flat colour, MS Paint doodle style.

PROMPT 95 [3:08–3:10]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman sits at a small camp table (rectangle on two legs) writing in a journal. The stickman: medium circle head, dot eyes directed downward at the journal, a neutral concentrated mouth. Right arm extended down to the table, holding a pen (thin stick with a point). Left arm resting on the table edge. Legs hanging under the table (two sticks hanging downward from the seat edge). The journal shows small lines of "writing" (short horizontal squiggles). Beside the journal, a small analogue clock icon on the table — but it has a red X through it (no clock allowed). Text at top: "NO CLOCK ALLOWED. HE TRACKED HIS OWN CYCLES." Flat colour, MS Paint doodle style.

PROMPT 96 [3:10–3:12]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman in bed (horizontal rectangle, pillow bump) in a cave environment (cave walls indicated by irregular dark navy border around the edge of the frame). The stickman: medium circle head on pillow, closed-eye marks (two short horizontal dashes), a peaceful small upward mouth (sleeping). Body line horizontal. Arms at sides. Legs extended. A small thought bubble from the sleeping stickman's head: inside the bubble, a simple clock shape with the text "SLEPT: 8 HRS?" A question mark after the hours. The stickman doesn't know how long they slept. Flat colour, MS Paint doodle style.

PROMPT 97 [3:12–3:14]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman waking up, stretching. The stickman: medium circle head, both arms raised above the head in a long stretch (both sticks raised high above the head circle, slightly outward — the classic morning stretch). Dot eyes half-open (tired waking up look — dots with curved lines below them, slightly squinting from brightness of thought). Mouth curved upward gently (mild pleasant awakening). Body upright. Legs stretching (one leg extended on the bed, one foot on the floor — mid-getting-out-of-bed motion). A question mark floats beside the head. Text: "EVERY MORNING — WHAT DAY IS IT?" Flat colour, MS Paint doodle style.

PROMPT 98 [3:14–3:16]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. An infographic calendar page — a simple rectangle outline with grid lines creating boxes for days (a simple 4x7 grid within the rectangle, like a month calendar). Most boxes are empty. A stickman stands beside the calendar, reaching toward it with a pen: medium circle head, dot eyes directed at the calendar, a focused straight mouth. Right arm extended, pen at the tip touching the calendar. Left arm at side. Legs together. But the calendar is WRONG — the stickman is marking a box in the middle of the month, but a red arrow points to where they ACTUALLY are on the calendar (further along). A gap between the stickman's guess and the actual position. Text: "HIS BEST GUESS." Flat colour, MS Paint doodle style.

PROMPT 99 [3:16–3:18]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A split frame. LEFT side: labelled "SIFFRE BELIEVED:" — a simple clock face showing a date/time early in the cave experience (day 25 style). A small stickman on the left: small circle head, calm dot eyes, neutral mouth — relaxed, thinking it's only been 25 days. RIGHT side: labelled "REALITY:" — a clock face showing a date much further along (day 58 style). A second small stickman identical to the first but with wide shocked eyes and an open O-mouth. The contrast between the two clocks is dramatic. A bold bold red arrow between the panels pointing right: "REALITY →." Flat colour, MS Paint doodle style.

PROMPT 100 [3:18–3:20]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A large bold "58" occupies the upper half of the frame — enormous hand-lettered numerals, slightly wobbly edges (MS Paint). Below the "58": "DAYS UNDERGROUND." Below that: "HE THOUGHT: 25 DAYS." The "25" in a smaller red number with a red X through it. In the lower portion of the frame: a small stickman holding both hands up to the sides of their face in a Home Alone/shocked gesture. The stickman: medium circle head, enormous wide dot eyes (the largest eye dots in the video — completely shocked), a wide-open curved-down O-mouth (horror/shock). Both arms bent upward with the sticks pressing flat against both cheeks of the head circle. Legs apart, body rigid with shock. Flat colour, MS Paint doodle style.

PROMPT 101 [3:20–3:22]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A timeline bar stretching across the frame. The bar goes from "DAY 1" on the left to "DAY 58" on the right. Two markers on the bar: a small stickman icon at the DAY 25 position (with a speech bubble saying "I AM HERE") and a separate red arrow pointing to the DAY 58 position (labelled "ACTUAL POSITION"). The gap between the two positions is highlighted with a thick yellow bracket. Text above the bracket: "33 DAYS LOST." The DAY 25 stickman: tiny circle head, dot eyes, one arm raised pointing down at the bar. Flat colour, MS Paint doodle style.

PROMPT 102 [3:22–3:24]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman packing up camp — dismantling a simple tent (triangle outline being folded, indicated by the triangle now having dotted lines suggesting it's partially collapsed). The stickman: medium circle head, dot eyes directed at the tent, a slight upward mouth (eager to leave, excited). Left arm reaching toward the tent. Right arm holding a small bag shape (a rectangle with a handle line). Legs in active walking stance. But on the wall above the tent, a countdown is visible: "33 DAYS AHEAD OF SCHEDULE." The "AHEAD OF" is crossed out with red and replaced by "BEHIND BY." Text: "HE THOUGHT HE WAS DONE EARLY." Flat colour, MS Paint doodle style.

PROMPT 103 [3:24–3:26]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman climbing up a rope out of the cave — the reverse of the descent. The rope is a thick vertical line. The stickman: medium circle head, dot eyes directed upward (toward the surface), a determined straight-line mouth. Both arm sticks gripping the rope (raised above head, both on the rope). Legs bent slightly (climbing posture). The cave environment (dark navy below) transitions to white above the horizontal ground line (the surface). A small yellow sun shape appears in the upper right corner of the white surface area. Text: "DAY 58 — RETURNING TO THE SURFACE." Flat colour, MS Paint doodle style.

PROMPT 104 [3:26–3:28]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman emerging from a cave mouth — they are half above and half below the ground line (the horizontal surface line). Upper body above the ground in white space (sunlight), lower body still below in the dark. The stickman: medium circle head above the line, dot eyes squinting dramatically (two small dashes — reacting to light after long darkness), a downturned grimace-to-smile transition (mouth halfway between distress and joy). Both arms gripping the cave edge (both sticks pressed on either side of the cave opening hole). Text: "FIRST LIGHT IN TWO MONTHS." Flat colour, MS Paint doodle style.

PROMPT 105 [3:28–3:30]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. Two stickman figures facing each other. LEFT STICKMAN: Siffre — medium circle head, dot eyes wide (astonished), a strongly open O-shaped mouth, arms raised in surprise/shock, legs apart. He holds a small journal (rectangle) in one hand. RIGHT STICKMAN: a RESEARCHER in a lab coat (indicated by a long rectangular shape extending to just above the knee sticks — the lab coat — drawn behind the body line with a button dot at the collar). The researcher stickman: medium circle head, dot eyes slightly wide (trying to contain excitement — slightly raised eyebrow marks), a slight upward line mouth (restrained amazement). The researcher holds a clipboard (a rectangle). Between them: a bold "58!" on the left and "25?" on the right, with a double-headed arrow and "???" between. Flat colour, MS Paint doodle style.

PROMPT 106 [3:30–3:32]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. An infographic: a large brain shape (yellow, fold lines) with a clock INSIDE the brain. The clock has standard hands but they are clearly off by a large margin (hands pointing to a very different time than the corner of the frame's actual external clock). An external reference clock sits outside and above the brain (labelled "ACTUAL TIME"). An internal clock sits inside the brain (labelled "BRAIN'S TIME"). Two arrows connect them showing the discrepancy, with a large gap highlighted in red. Text below the brain: "HIS INTERNAL CLOCK LOST HALF THE TIME." Flat colour, MS Paint doodle style.

PROMPT 107 [3:32–3:34]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman in a lab coat (rectangular coat outline to knee length, a collar line at top) studying a large chart on a wall. The chart shows two parallel timelines — one labelled "SIFFRE'S LOG" (the shorter line, representing 25 days of perceived time) and one labelled "CALENDAR" (the longer line, 58 days of actual time). The researcher stickman: medium circle head, dot eyes directed at the chart (eyes toward the chart on the wall), a slightly open mouth (analytical interest). Right arm raised, pointing at the discrepancy gap. Left arm holds a clipboard (small rectangle). Legs apart, stable stance. Text: "THE DATA WAS UNDENIABLE." Flat colour, MS Paint doodle style.

PROMPT 108 [3:34–3:36]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A large "x2" in the centre of the frame — enormous bold characters, hand-lettered style, slightly wobbly. Below: "HIS PERCEIVED TIME WAS HALF REAL TIME." To the left of the x2: a small stack of 25 tiny rectangles (representing 25 perceived days). To the right: a stack of 58 tiny rectangles (representing 58 real days). The left stack is obviously shorter than the right stack. No stickman. Bold graphic infographic. Flat colour, MS Paint doodle style.

PROMPT 109 [3:36–3:38]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman sits hunched at a table, studying their journal versus a real calendar. The stickman: medium circle head bent forward (dot eyes down looking between the two documents on the table), a strongly downturned mouth (devastated realisation). Right arm extended over the journal. Left arm extended over the calendar. Legs hanging from the seat. The table has the journal on the left (stickman's journal, labelled "MY LOG") and the calendar on the right (labelled "ACTUAL DATE"). The gap is visible as empty space between the two documents. Text above: "HIS MIND HAD BEEN LIVING IN A DIFFERENT TIME." Flat colour, MS Paint doodle style.

PROMPT 110 [3:38–3:40]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman walking forward confidently — but their shadow (cast behind them to the left) shows a stickman walking in the OPPOSITE direction. This represents the dissociation between internal experience and external reality. The walking stickman: medium circle head, dot eyes forward (focused ahead), neutral straight mouth, arms in walking swing (right arm forward, left arm back), legs in stride. The shadow (navy blue filled silhouette): same scale but walking leftward — head circle to the left, arms swinging opposite way. Text: "INTERNAL AND EXTERNAL — OUT OF SYNC." Flat colour, MS Paint doodle style.

PROMPT 111 [3:40–3:42]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A group of THREE researcher stickmen gathered around a table looking at a large paper (a rectangle spread across the table). All three researchers: medium circle heads, dot eyes directed downward at the paper on the table, slightly open mouths (various stages of amazed). RESEARCHER 1 (left): arms bent, leaning on the table — both sticks on the table surface. RESEARCHER 2 (centre): one arm pointing at the paper, other arm at side. RESEARCHER 3 (right): both arms crossed over chest (arms crossing the body line at mid-torso), stepping back slightly. All wearing lab coat indicators (rectangle outlines to the knee). Text: "THE SCIENTIFIC WORLD WAS STUNNED." Flat colour, MS Paint doodle style.

PROMPT 112 [3:42–3:44]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A bold statement frame. Centre: a simple rectangular border (thick double outline). Inside: "WITHOUT LIGHT YOUR BRAIN DOES NOT JUST LOSE TRACK OF TIME." Below that: "IT LOSES THE EXPERIENCE OF IT." The second sentence is larger and bolder than the first. No stickman. Clean typographic panel in MS Paint hand-lettered style. Below the box, a thin shadow below each letter (adding weight to the statement). Flat black on white. MS Paint doodle style.

PROMPT 113 [3:44–3:46]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman holding a balloon on a string — but the balloon has "TIME" written inside it. The stickman: medium circle head, dot eyes directed at the balloon (upward — balloon is above the head), a slightly open worried mouth. Right arm raised upward at 90 degrees, holding the balloon string (a thin vertical line from hand to balloon oval above). Left arm at side. Legs together. The balloon is drifting slightly to one side (the string has a slight curve suggesting the balloon is floating away). A small red arrow points at the string near the hand: "LOSING GRIP." Text: "TIME AS A PHYSICAL THING YOU CAN HOLD." Flat colour, yellow balloon, MS Paint doodle style.

PROMPT 114 [3:46–3:48]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A timeline comparison: TOP TRACK (labelled "CALENDAR TIME"): a straight horizontal arrow with evenly spaced tick marks. BOTTOM TRACK (labelled "SIFFRE'S TIME"): a shorter horizontal arrow with more widely spaced tick marks — each perceived day takes up more physical space on the arrow than the calendar day. The two tracks are the same physical width on the frame, but the bottom track ends at "DAY 25" while the top track extends to "DAY 58." A bracket between the endpoints shows the gap: "33 MISSING DAYS." No stickman. Infographic style, flat colour, MS Paint doodle style.

PROMPT 115 [3:48–3:50]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman sits on the ground, knees up, head in hands. The stickman: medium circle head, both arms bent upward with the sticks pressing flat against the face (the "head in hands" position — both elbows up, hands covering the lower face area). Eyes visible above the hands: very large wide dot circles (the shock hasn't worn off). Mouth hidden by hands but the overall posture communicates devastation. Body upright (back relatively straight despite the arms being up). Legs bent, knees raised. Text: "58 DAYS. FELT LIKE 25." Flat colour, MS Paint doodle style.

PROMPT 116 [3:50–3:52]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. An abstract visualisation of time contraction. On the LEFT: a long horizontal bar labelled "58 REAL DAYS" — the bar is long, spanning most of the left side of the frame. On the RIGHT: the same bar but squished/compressed — now much shorter — labelled "FELT LIKE 25 DAYS." An arrow labelled "BRAIN COMPRESSION" points from the long bar to the short bar. The compression is shown by the bar being squashed with accordion-fold lines in the middle (the bar being physically compressed). No stickman. Abstract infographic, flat colour, MS Paint doodle style.

PROMPT 117 [3:52–3:54]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A large question box in the centre of the frame (rectangle outline, thick lines). Inside: "IF LIGHT CALIBRATES TIME..." Below that: a downward arrow. Below the arrow: "WHAT CALIBRATES YOU?" This second line is in larger, bolder text. Beneath the box: a small stickman looking up at the box with an upturned head. The stickman: small circle head tilted back (looking up), dot eyes directed at the text in the box, a slightly open pondering mouth. Arms hanging at sides. Legs together. Flat colour, MS Paint doodle style.

PROMPT 118 [3:54–3:56]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman reaching toward a light switch on a wall. The wall: a vertical line on the left side of the frame. The light switch: a small rectangle on the wall with a toggle shape inside. The stickman: medium circle head, dot eyes directed at the switch (eyes toward the left), an eager hopeful upward mouth curve (wanting to turn on the light). Right arm fully extended leftward toward the switch (reaching). Left arm at side. Legs stepping left (left leg forward, right leg behind). Above the stickman, a faint outlined sun shape (the longed-for light). Text: "THE LESSON: LIGHT IS NOT A LUXURY." Flat colour, MS Paint doodle style.

PROMPT 119 [3:56–3:58]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman and their reflection in a pool of water (drawn as a wavy horizontal line in the lower portion of the frame, with the stickman's inverted silhouette below it in navy blue). The standing stickman: medium circle head, dot eyes directed downward at the reflection, a thoughtful neutral mouth, arms loosely at sides, legs apart. The reflection (in navy, below the water line): same shape but inverted. But the reflection's mouth is a downward curve (the reflection looks sadder than the real face). Text: "SIFFRE HAD STARTED TO CHANGE INSIDE." Flat colour, navy and white, MS Paint doodle style.

PROMPT 120 [3:58–4:00]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A before-and-after of the same stickman. LEFT (labelled "DAY 1"): stickman standing upright, full energy — medium circle head, bright wide-open dot eyes, upward-curved smile, arms at sides with hands open (stick finger lines extended — engaged, ready), legs firmly apart. RIGHT (labelled "DAY 58"): same stickman but showing wear — same medium circle head but tilted slightly, dot eyes half-closed and directed slightly downward (fatigue and sadness combined), a flat straight mouth (all expression drained), arms hanging slightly lower (the arm sticks angled down at a steeper angle than day 1), legs slightly closer together (less energy, less certainty). Flat colour, MS Paint doodle style.

PROMPT 121 [4:00–4:02]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A large "1962" in bold hand-lettered style in the upper portion of the frame, with "EXPERIMENT COMPLETE" below it. A thick underline beneath the text. Below the underline: a simple cave cross-section (wavy oval outline, dark edge, white interior) with a small stickman climbing out of it — the stickman is at the mouth of the cave, one arm reaching upward out of the cave. The stickman: small circle head, dot eyes directed upward, a determined straight mouth, one arm reaching up and out. The small stickman represents Siffre's emergence. Text below the cave: "BUT SIFFRE WASN'T DONE." Flat colour, MS Paint doodle style.

PROMPT 122 [4:02–4:04]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman at a lectern/podium — a triangular podium shape (a trapezoid, wider at base). The stickman stands at the podium: medium circle head, dot eyes forward (addressing an audience), a confident straight-line mouth. Left arm rests on the podium surface. Right arm raised slightly (gesturing while speaking). Legs apart, standing confidently behind the podium. In front of the podium: a small audience of three tiny stickmen (three small circle heads in a row with tiny dot eyes directed at the speaker). A speech bubble from the speaker stickman: "WE GO BACK." Flat colour, MS Paint doodle style.

PROMPT 123 [4:04–4:06]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. Bold graphic text fill. The frame shows the year "1972" in enormous hand-lettered bold numbers — the numbers taking up 70% of the frame. Below the numbers in smaller but still bold text: "10 YEARS LATER." And beneath that: "SIFFRE RETURNED." A very thin small stickman at the very bottom of the frame, tiny relative to the numbers: small circle head, dot eyes upward (looking at the numbers/year), arms at sides, legs together. Flat colour, MS Paint doodle style.

PROMPT 124 [4:06–4:08]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A simple map of Texas, USA — drawn as an irregular polygon in thick black lines (Texas's distinctive shape, simplified). A bold X marks a location in the western part (Midnight Cave, Del Rio, Texas). An arrow pointing to the X: "MIDNIGHT CAVE — TEXAS." No stickman. The map fills most of the frame. The state outline is hand-drawn and slightly wobbly. A small US outline in the corner (tiny, for context) with Texas highlighted. Flat colour, MS Paint doodle style.

PROMPT 125 [4:08–4:10]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. Cross-section of an even deeper cave than before. The surface line at the top of the frame with mountains above. The cave below the surface is deeper (indicated by a longer distance from the surface line to the cave). The cave interior: an irregular white blob, deeper and more isolated. Inside: a tiny stickman — very small (showing how deep and isolated). Tiny circle head, dot eyes, arms at sides. Beside the cave depth measurement: "SIX MONTHS." Bold text. Flat colour, MS Paint doodle style.

PROMPT 126 [4:10–4:12]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman packing an enormous backpack — a large rectangle pack drawn behind the body, straps over the shoulders (curved lines over the shoulder sticks). The stickman: medium circle head, dot eyes directed forward (determined), a slight upward mouth (committed, ready). Body upright. Both arms gripping the backpack straps (both sticks raised slightly, gripping imaginary straps at shoulder level). Legs apart, weight slightly forward. Beside the stickman, a checklist: "□ NO CLOCK  □ NO CALENDAR  □ NO LIGHT  □ 6 MONTHS." Each item in small black caps. Flat colour, MS Paint doodle style.

PROMPT 127 [4:12–4:14]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman says goodbye at a cave entrance — a cave opening oval shape in the right of the frame. The stickman: medium circle head facing left (away from cave), toward TWO smaller stickman figures representing the research team. One arm of the main stickman raised in a wave (right arm raised straight up — goodbye). Left arm at side. Legs together. The two research team stickmen (left side): small circle heads, both with dot eyes directed at the main stickman, both with one arm raised in return wave. All three have neutral to slightly solemn mouths (this is serious). Text: "THE SURFACE TEAM WOULD WAIT FOR SIX MONTHS." Flat colour, MS Paint doodle style.

PROMPT 128 [4:14–4:16]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. The cave interior — dark navy fill for the walls, white centre. A stickman sits inside with very basic setup — a cot (simple rectangle), a small table, a few boxes. The stickman: medium circle head, dot eyes surveying the space, a neutral mouth (assessing the situation). Arms loose at sides. Legs apart. The cave has no windows — just solid navy walls all around the white central area. Text: "EVERYTHING WAS PROVIDED — EXCEPT LIGHT." A small faint sun outline is drawn in the upper corner but crossed out with red X. Flat colour, MS Paint doodle style.

PROMPT 129 [4:16–4:18]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman on a phone (a simple rectangle held to the ear — arm raised, holding the rectangle to the right side of the head). The stickman: medium circle head, dot eyes directed upward-left (concentrating on speaking), a neutral talking mouth (slightly open horizontal line). Left arm at side. Legs apart, standing. On the other end of the "phone call" (represented by a separate speech bubble in the upper right of the frame with a phone icon): a researcher stickman with a clipboard. Text from the main stickman's phone: "CHECK-IN — DAY 1." Flat colour, MS Paint doodle style.

PROMPT 130 [4:18–4:20]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. An infographic: a simple 6-month calendar grid (six vertical columns for months, each with a stack of 30 small boxes for days). The months are labelled "M1" through "M6." In M1, the first few boxes have a small checkmark. The rest of the boxes are empty. A stickman stands to the right of the grid: medium circle head, dot eyes looking at the grid, right arm reaching to check the first box, left arm at side. Legs together. Text: "205 DAYS. ALONE. IN THE DARK." Below: "HE ONLY HAD TO DO IT ONCE." Flat colour, MS Paint doodle style.

PROMPT 131 [4:20–4:22]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman lying in a sleeping bag (an elongated oval outline with the stickman inside, just the head poking out). The stickman: medium circle head sticking out of the top of the sleeping bag oval, dot eyes half-open (drowsy), a slightly open tired mouth. The sleeping bag oval is flat yellow. The cave walls are navy around the edges of the frame. Beside the sleeping bag, a small notebook with the word "HOUR?" scratched on the cover (suggested by wavy lines). No clock visible. Text: "FIRST SLEEP UNDERGROUND — TRACKING BEGINS." Flat colour, MS Paint doodle style.

PROMPT 132 [4:22–4:24]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A bold "DAY 1 OF 205" text panel — numbers in large bold hand-lettered style. Below: a simple visual — a long horizontal bar representing 205 days. The first two units of the bar are filled solid black (day 1 beginning). The rest of the bar is an empty outline, representing all the days ahead. A tiny stickman stands at the very left end of the bar: tiny circle head, dot eyes directed rightward along the bar's length (looking at the enormous empty space ahead), a tiny straight mouth. The bar stretches off to the right with no visible end. Flat colour, MS Paint doodle style.

"""

with open('/home/user/OG-youtube/264_image_prompts.txt', 'a') as f:
    f.write(content)
print("Part 3 appended: Prompts 89-132")
