content = """
══════════════════════════════════════════════════════════
SECTION 5: SIFFRE 1972 — SIX MONTHS UNDERGROUND (Prompts 133–176 | 4:24–5:52)
══════════════════════════════════════════════════════════

PROMPT 133 [4:24–4:26]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. The cave interior scene (navy wall borders, white centre). A stickman wakes up after what he believes is a normal night of sleep. The stickman: medium circle head, dot eyes blinking open (one eye fully open as a dot, the other still half-closed — one eye at a time waking up), a slow upward mouth curve (morning stretch feeling). Both arms raised above the head in a stretch. One leg stretching out long (extended), one leg bent. A small notebook on a table beside the cot has "MORNING? NIGHT?" written on it (wavy lines suggesting the question). Text: "EVERY WAKING WAS A GUESS." Flat colour, MS Paint doodle style.

PROMPT 134 [4:26–4:28]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A simple 24-hour wheel diagram (a circle divided into 24 equal slices, alternating yellow and white for day/night). Overlaid on the wheel: a second dotted-line circle, slightly misaligned (rotated by about 4 hours from the solid one). The dotted circle is red. Text labels: "EARTH'S 24-HOUR CYCLE" (solid) and "SIFFRE'S SHIFTING CYCLE" (dotted red). The misalignment grows: an arrow on the red dotted circle showing it rotating further away. Text below: "DAY 30: THE DRIFT BEGINS." No stickman. Flat colour, MS Paint doodle style.

PROMPT 135 [4:28–4:30]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman sleeping for an unusually long time — shown via an exaggerated "ZZZ" sequence above the sleeping stickman's head, with the Z's growing progressively larger (small Z, medium Z, large Z, HUGE Z). The stickman: medium circle head lying on a simple pillow (rectangle), closed-eye marks (two horizontal dashes), a slack open mouth (deep heavy sleep — mouth slightly open with a tiny circle gap). Body line horizontal, arms along sides, legs straight. The ZZZ sequence towers above the figure. Text: "12 HOURS. THEN 14. THEN MORE." Flat colour, MS Paint doodle style.

PROMPT 136 [4:30–4:32]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. An infographic showing sleep duration vs calendar day. A bar chart: horizontal axis labelled "CAVE DAY," vertical axis labelled "HOURS SLEPT." The bars start at normal height (around 8 hours for the early bars) and progressively get taller as the cave days increase — by day 60, the bars are reaching 14-16 hours. The bars are yellow fill with black outlines. The 8-hour line is marked with a dotted green line ("NORMAL"). Everything above the green line is highlighted red. No stickman. Flat colour, MS Paint doodle style.

PROMPT 137 [4:32–4:34]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman eating a meal at a small table — but outside the window (which would normally show day or night), there is only a solid navy rectangle (no external light cue). The stickman: medium circle head, dot eyes directed at the plate, a slow methodical neutral mouth (eating without enjoyment, eating by routine). Right arm holding a fork (stick with three tiny prongs at the end). Left arm resting on table. Legs hanging. The table has a plate circle and a glass rectangle. Above, a thought bubble: a simple sun/moon question mark floating inside. Text: "IS IT BREAKFAST OR DINNER?" Flat colour, MS Paint doodle style.

PROMPT 138 [4:34–4:36]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman awake in the dark for 36 hours straight — shown via an enormous counter above the figure: "36 HRS AWAKE" in bold red. The stickman: medium circle head, dot eyes extremely bloodshot-looking (two dot pupils with tiny red lines radiating from each dot — doodle-style red veins), a slight downward line mouth (profound fatigue). Body upright but slightly curved (stooping). Both arms slightly raised, slightly bent — the posture of someone running on empty but too wired to sleep. Legs slightly wider than shoulder width (for balance). Dark navy shadows under the eyes (small navy semi-circle under each eye dot). Text: "DAY 45: SLEEP CYCLES EXPANDING." Flat colour, MS Paint doodle style.

PROMPT 139 [4:36–4:38]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A split timeline comparison. TOP: a normal 24-hour cycle wheel. BOTTOM: Siffre's expanding cycle — the same wheel but stretched out to 48 hours (the circle is the same size, but the day/night dividing line has moved so that each "day" now takes 48 hours rather than 24). The BOTTOM circle has stretched labels around its perimeter — the hours stretched out to 48. A bold red "48 HOURS" label on the bottom circle, replacing "24 HOURS." Text between them: "HIS BODY INVENTED ITS OWN CLOCK." No stickman. Flat colour, MS Paint doodle style.

PROMPT 140 [4:38–4:40]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman staring at a blank cave wall (the wall: a flat navy rectangle on the right side of the frame). The stickman: medium circle head, dot eyes directed at the wall (wide, slightly vacant — the beginning of a dull stare), a completely flat straight-line mouth (dissociation beginning). Body upright but utterly still — no dynamic arm position, no weight-shift. Both arms hang perfectly straight at sides. Both legs together, feet touching. The posture communicates total stillness. Text above: "DAY 60: NOTHING LEFT TO LOOK AT." Flat colour, MS Paint doodle style.

PROMPT 141 [4:40–4:42]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman talking to an imaginary companion — TWO stickman figures, but the RIGHT one is drawn in dotted grey lines rather than solid black (indicating it is imaginary, not real). The REAL stickman: medium circle head, dot eyes directed at the imaginary figure, an animated slightly open mouth (talking). Arms: one raised in a gesturing-while-talking position (arm at 60 degrees upward, elbow bent slightly). Legs apart, engaged. The IMAGINARY stickman: dotted-line circle head, dotted body and arms — same pose as listening, but pale. Between them: a speech bubble from the real stickman. Text: "DAY 65: THE COMPANIONS BEGAN." Flat colour, black and grey on white, MS Paint doodle style.

PROMPT 142 [4:42–4:44]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman writing intensely in a journal. The stickman: medium circle head, dot eyes directed sharply downward (intense focus), eyebrow marks above the eyes as two short angled lines pointing toward the centre (furrowed concentration). A tight, closed straight-line mouth. Body leaning forward (body line at 20 degrees from vertical, leaning toward the table). Right arm pressing down on the open journal (rectangle), with the pen stick making multiple rapid strokes (indicated by short parallel lines on the page — writing fast). Left arm on the table for support. Legs pressed against the chair legs (bent at knee, lower legs behind). Text: "WRITING EVERYTHING DOWN. EVERYTHING." Flat colour, MS Paint doodle style.

PROMPT 143 [4:44–4:46]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. An internal feelings infographic — a stickman outline (the same circle head and stick body) but the inside of the body is divided into a pie chart. The pie segments have labels: "LONELINESS" (largest segment, red), "CONFUSION" (second largest, yellow), "ROUTINE COMFORT" (small sliver, green), "FEAR" (medium segment, navy). The pie chart is drawn inside the body outline. The stickman's face above: medium circle head, dot eyes neutral but tired, a flat straight mouth. Flat colour, MS Paint doodle style.

PROMPT 144 [4:46–4:48]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman standing in the cave — but now the cave walls have SHAPES on them. Simple doodle shapes (a flower, a stick-figure drawing of a person, simple geometric patterns) are drawn on the navy cave wall as if the stickman has been drawing on the walls to pass time. The stickman: medium circle head, dot eyes directed at the wall, one arm raised touching the wall art (right arm extended left, touching the wall with a pen or finger), a small content upward mouth curve (small joy in creativity). Text: "DAY 70: DECORATING THE CAVE WALLS." Flat colour, MS Paint doodle style.

PROMPT 145 [4:48–4:50]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. An upward-then-plunging line graph. The vertical axis: "MOOD." Horizontal axis: "CAVE DAYS (1–205)." The graph line starts at a moderate level on day 1, dips slightly through the first month, partially recovers, then begins a longer gradual decline around day 60, with a sharp drop around day 79 (marked with a bold red circle and the note "CRISIS — DAY 79"), then a flat low level for the remainder. The line is thick black. The crisis point is highlighted with a red circle and arrow. No stickman. Clean chart, flat colour, MS Paint doodle style.

PROMPT 146 [4:50–4:52]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman on the floor in a foetal-like position — lying on one side, knees pulled up toward the chest, arms wrapped around the knees. The stickman: medium circle head lying on the floor (sideways), dot eyes pressed tightly shut (two short dashes), a strongly downturned curved mouth (deep sorrow, crying posture). Body line curled. Knees brought up (lower leg sticks angled toward the chest). Arms wrapped around the knees (sticks curving). The cave walls (navy border) close in around the figure from all sides. Text: "DEPRESSION SET IN." Flat colour, MS Paint doodle style.

PROMPT 147 [4:52–4:54]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman standing at a phone on the wall (a simple rectangle handset on a wall bracket). The stickman: medium circle head, dot eyes directed at the phone (eyes left toward the phone), a strongly downturned mouth (distressed, about to cry). One arm reaching toward the phone. Legs stepping toward it. The phone on the wall has a small bell shape and two horizontal lines suggesting it is a communication device. A speech bubble from the stickman: "I WANT TO STOP." Below: "DAY 79." In bold red. Flat colour, MS Paint doodle style.

PROMPT 148 [4:54–4:56]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A phone call visualisation — two stickman figures connected by a wavy line (the telephone line). LEFT STICKMAN (Siffre in cave — navy background behind him): small circle head, dot eyes downward and red-tinged (two tiny red lines radiating from each eye dot — crying), strongly downturned mouth. RIGHT STICKMAN (researcher on surface — white background behind him): small circle head, dot eyes focused (listening carefully), a serious neutral straight mouth. Both stickmen hold small rectangle phones to their ears (left stickman: right arm raised, phone to right ear; right stickman: left arm raised, phone to left ear). Text between them: "DAY 79: THE CALL." Flat colour, MS Paint doodle style.

PROMPT 149 [4:56–4:58]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. The researcher stickman (on the surface) in a pleading-with-firmness gesture — holding the phone to the ear with one hand, the other hand raised with all fingers spread (the "please, wait" gesture). The researcher stickman: medium circle head, dot eyes earnest and direct (slightly larger dots — serious intensity), a gentle straight-line mouth (controlled, encouraging). Right arm raised with phone. Left arm raised with spread-finger gesture. Legs apart — weight forward (leaning into the conversation). A speech bubble from the researcher: "YOU HAVE COME THIS FAR." Text: "THE SCIENTISTS PERSUADED HIM TO CONTINUE." Flat colour, MS Paint doodle style.

PROMPT 150 [4:58–5:00]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman back in the cave, standing again after the phone call — but the posture is slightly different than before. The stickman: medium circle head, dot eyes directed forward (not sideways, not downward — looking ahead again), a flat but resolved straight-line mouth (not happy, but committed). Body upright. Both arms hanging at sides but slightly further from the body than before (a slight stiffness — regathering oneself). Legs apart in a stable stance. Behind the stickman, the cave walls (navy). A small speech bubble: "..." — silence, recommitment. Text: "HE STAYED." Flat colour, MS Paint doodle style.

PROMPT 151 [5:00–5:02]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. An infographic — a running total counter. A large rectangle box in the centre. Inside: "DAYS UNDERGROUND: 100" in large hand-lettered numbers. Below that: "DAYS SIFFRE THINKS HAVE PASSED: ~50." The discrepancy is highlighted — both numbers side by side with a bold red arrow between them pointing DOWN (to show the internal time is lower than actual). No stickman. Bold numerical infographic. Flat colour, MS Paint doodle style.

PROMPT 152 [5:02–5:04]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman sits staring at a spider on the wall — a tiny simple spider doodle (circle body, eight lines for legs) on the navy cave wall. The stickman: medium circle head, dot eyes directed at the spider, a slightly upward-curved mouth (bemused, small joy from a tiny creature). Right arm raised, finger pointing at the spider. Left arm at side. Legs crossed (sitting cross-legged on the floor). A speech bubble: "HELLO." Text: "SMALL THINGS BECAME COMPANIONS." Flat colour, MS Paint doodle style.

PROMPT 153 [5:04–5:06]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman in a moment of hallucination. The stickman: medium circle head, dot eyes wide and staring (large filled black dots), a small open O-mouth (seeing something). In front of the stickman: a ghostly apparition drawn in pale grey dotted lines — the shape of a large human figure (not a stickman — a blurry amorphous person-shape). The apparition has no face, no detail — just an outline suggesting human form. Labelled in red: "NOT REAL." The stickman's arms are slightly raised at both sides (defensive, unsure). Legs frozen in place, feet together. Text: "DAY 110: HALLUCINATIONS." Flat colour, MS Paint doodle style.

PROMPT 154 [5:06–5:08]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A zoom-in infographic of a brain — the brain oval fills most of the frame. The visual cortex region (back of brain) is outlined with a dotted red circle and is GLOWING (three small radiating lines in yellow from the region). The temporal lobe region has a dotted orange circle. The prefrontal region has a dotted blue circle. All three labelled with arrows: "VISUAL CORTEX: GENERATING IMAGES," "TEMPORAL: TIME PROCESSING FAILED," "PREFRONTAL: DECISION-MAKING IMPAIRED." No stickman. Detailed brain zone diagram, flat colour, MS Paint doodle style.

PROMPT 155 [5:08–5:10]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman listening to music through simple headphones (two circles connected by an arc, one circle on each side of the head). The stickman: medium circle head, headphone circles on the sides, dot eyes half-closed (peaceful, the music is a comfort), a gentle upward-curved mouth (small pleasure). Body upright. Both arms loose at sides. Legs together. Musical note symbols float around the head (three eighth-note symbols at different heights around the head area). A speech bubble from the head: "THE MUSIC WAS THE ONLY COLOUR LEFT." Text at top: "DAY 120: FINDING SMALL ANCHORS." Flat colour, MS Paint doodle style.

PROMPT 156 [5:10–5:12]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. An infographic split showing what Siffre knew vs what was happening to him. Two columns: LEFT "WHAT HE FELT" — a stickman looking relatively okay (posture upright, expression flat but not alarmed). RIGHT "WHAT WAS HAPPENING" — a brain diagram with multiple red-circled problem zones, a clock with melting hands, a body temperature arrow pointing steeply down. He could feel some of it but not see all of it. Between the columns: a bold vertical dividing line. Flat colour, MS Paint doodle style.

PROMPT 157 [5:12–5:14]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman exercising — running in place (both legs bent at the knee alternately, one up, one down, the body bouncing slightly). The stickman: medium circle head with slight side-to-side tilt (movement), dot eyes forward (focused on exercise), a determined straight mouth. Body line slightly dynamic (not perfectly vertical — movement). Right arm swinging forward, left arm swinging back (running arm motion). Legs alternating. Around the figure: small motion lines on the legs indicating speed. Text: "DAY 130: EXERCISE TO STAY SANE." Flat colour, MS Paint doodle style.

PROMPT 158 [5:14–5:16]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman counting with fingers — both hands held up, all ten fingers extended as sticks. The stickman: medium circle head, dot eyes directed downward at the hands (counting carefully), lips pressed together in a focused expression (closed mouth, straight line). Both arms raised to chest height, both hands open and extended (all stick fingers spread out — representing the counting gesture). Legs together, standing. A speech bubble: "WHAT DAY IS IT?" Text: "DAY 140: COUNTING BECAME THE OBSESSION." Flat colour, MS Paint doodle style.

PROMPT 159 [5:16–5:18]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. The cave scene — navy walls bordering the white interior. The stickman sits against the cave wall (leaning back against the navy border), in a moment of complete stillness. The stickman: medium circle head tilted slightly back (resting against wall), dot eyes directed upward at the cave ceiling (blank, staring at nothing), a completely flat horizontal line mouth (no expression — void). Arms lying flat at sides, slightly away from the body (collapsed posture). Legs straight out in front (extended along the cave floor). Text: "DAY 150: JUST BEING." Flat colour, MS Paint doodle style.

PROMPT 160 [5:18–5:20]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman at the cave phone again — a rectangle handset on the wall. But this time the stickman is not in distress — they're calm. The stickman: medium circle head, dot eyes directed at the phone (right), a flat neutral mouth (quiet, matter-of-fact). Right arm reaching toward the phone casually (not urgently). Left arm at side. Legs apart, easy stance. A speech bubble: "STILL HERE." And next to the phone, a calendar-like tally: four vertical lines crossed with a diagonal (five marks), repeated — tally marks. Text: "DAY 160: ROUTINE CHECK-INS KEPT HIM TETHERED." Flat colour, MS Paint doodle style.

PROMPT 161 [5:20–5:22]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A bold counter panel. Large text: "DAY 175" in enormous hand-lettered numbers. Below: "SIFFRE BELIEVES: DAY ~87." Below that: a simple visual comparison — a bar reaching to 175 ticks, and a shorter bar reaching to 87 ticks. The gap between the bars (88 days) is highlighted with a red bracket labelled "88 DAYS LOST." A tiny stickman at the bottom of the frame: tiny circle head, dot eyes directed at the numbers, arms at sides. Flat colour, MS Paint doodle style.

PROMPT 162 [5:22–5:24]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. An emotional weather report panel — a stickman dressed as a news presenter standing in front of a weather map (a simple background rectangle with cloud and rain icons). The presenter stickman: medium circle head, dot eyes forward (addressing the viewer), a neutral-to-slight-downward mouth. Body upright. Left arm at side. Right arm raised, holding a pointer stick. Behind the stickman, the weather map shows: a large navy cloud over the entire map with rain lines below it, a red frowning face cloud, and a single tiny yellow sun in the corner. A label: "EMOTIONAL FORECAST: DAY 180 — GREY THROUGHOUT." MS Paint doodle style.

PROMPT 163 [5:24–5:26]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman looking at their own hand in fascination — arm raised, holding hand up in front of the face. The stickman: medium circle head, dot eyes directed at the raised right hand (eyes toward the right side of the head, angled at the hand). A slightly open O-mouth (mild wonder). Right arm raised to eye level, bent at elbow, holding the hand up to look at it. Left arm at side. Legs apart. A thought bubble from the head: "AM I STILL ME?" Text: "DAY 185: IDENTITY BEGINS TO BLUR." Flat colour, MS Paint doodle style.

PROMPT 164 [5:26–5:28]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A split brain diagram — the brain oval cut down the middle. LEFT HALF labelled "WHAT HE REMEMBERS": shows a small calendar icon with a cross through most of the days (most time forgotten or unclear). RIGHT HALF labelled "WHAT ACTUALLY HAPPENED": shows the same calendar but with all boxes filled (all days present). The gap between the two halves is stark — the LEFT side's calendar is nearly blank, the RIGHT is full. A bold line down the brain's centre. No stickman. Flat colour, MS Paint doodle style.

PROMPT 165 [5:28–5:30]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman making tally marks on a cave wall (a navy rectangle on one side of the frame). The stickman: medium circle head, dot eyes directed at the wall (left), a focused neutral mouth. Right arm raised, etching tally marks on the wall (five marks visible — four verticals and a diagonal cross). Left arm at side. Legs together, leaning slightly toward the wall. On the wall, many groups of tally marks are already visible (four or five groups of five). Text: "HE KEPT COUNTING. THE WALL KNEW MORE THAN HE DID." Flat colour, MS Paint doodle style.

PROMPT 166 [5:30–5:32]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman dreaming while sleep-deprived — hunched on a chair with eyes closed but clearly not comfortable (not in bed). The stickman: medium circle head drooping forward (body line still upright, but head tilted far forward — nodding off on the chair). Closed-eye marks (two short dashes). A slight downward mouth (not peaceful sleep — troubled sleep). Both arms loosely hanging off the armrests of the chair (two sticks hanging at 45 degrees from the body, draped over imaginary chair arms). Legs slightly apart, feet on the floor. The dream bubble above is chaotic and navy-filled — dark dream content. Text: "SLEEP WITHOUT STRUCTURE." Flat colour, MS Paint doodle style.

PROMPT 167 [5:32–5:34]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. An infographic showing the expanded sleep cycle by day 150. A circular sleep cycle diagram (two rings: outer ring = a 48-hour cycle label, inner ring = showing alternating AWAKE and SLEEP segments). The AWAKE segment takes up 36 hours of the circle. The SLEEP segment takes up 12-16 hours. The proportions are clearly abnormal compared to the small normal diagram inset (a small circle in the corner showing the normal 24-hour split: 16 hours awake, 8 hours sleep). No stickman. Flat colour, MS Paint doodle style.

PROMPT 168 [5:34–5:36]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman reacting to a small sound in the cave — a bat flying overhead (a simple bat shape: two curved wings and a small oval body, drawn in black outline). The stickman: medium circle head turned upward (dot eyes directed upward at the bat), a slightly startled expression (eyes wider, mouth a small O — surprised). Right arm raised defensively over the head (arm bent, stick raised above head to cover). Left arm at side. Legs apart, stepping back slightly. A speech bubble: "HELLO?" The bat is tiny relative to the stickman (just a small doodle at the top of the frame). Text: "ANYTHING ALIVE WAS COMPANY." Flat colour, MS Paint doodle style.

PROMPT 169 [5:36–5:38]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman standing in the cave interior (navy borders), both arms stretched outward horizontally (arms at 90 degrees to the body, fully extended to both sides — wingspan pose). Head tilted slightly back. The stickman: medium circle head, dot eyes directed upward at the cave ceiling, a wide open upward-curved mouth (a moment of joy, release). Legs slightly apart. The pose is the freest, most expansive body language of the entire sequence. Text: "DAY 190: MOMENTS OF STRANGE JOY." Flat colour, MS Paint doodle style.

PROMPT 170 [5:38–5:40]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A simple equation panel. Top: "205 DAYS" in enormous bold numbers. Below: "÷ 2 =". Below: "~100 DAYS" in bold red (what Siffre thought he'd experienced). Below that: a large bold red question mark. Then: "THAT IS WHAT DARKNESS DID TO TIME." The equation format is clean, centred, and stark. No stickman. Flat colour, black and red, MS Paint doodle style.

PROMPT 171 [5:40–5:42]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. The cave exit scene — the cave mouth (an oval opening, the outside of it showing white, the inside showing navy). A stickman just emerging from the cave, standing half-in, half-out. The stickman: medium circle head at the cave mouth boundary, dot eyes squinting tightly shut (two short curved dashes — reacting violently to sunlight after 205 days), hands raised to face (both arm sticks raised to cover the eye area of the head circle). Legs one inside cave, one outside. A bold yellow star-burst in the upper right corner — the sun, overwhelming. Text: "DAY 205: THE SURFACE." Flat colour, MS Paint doodle style.

PROMPT 172 [5:42–5:44]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. Two stickman figures — Siffre and a researcher — shaking hands. Their arms meet in the middle of the frame. SIFFRE (left): medium circle head, squinting eyes (small dashes still adjusting to light), a huge open-mouth curved-upward smile (the biggest smile in the video). LEFT arm extended rightward for handshake. Right arm loosely at side. Legs apart, weight forward. RESEARCHER (right): medium circle head, wide open dot eyes (moved to tears, two tiny dots at the bottom of the eye area suggesting tears), a wide upward-curved smile. Right arm extended leftward for handshake. Left arm raised with a clipboard. Legs apart, leaning forward. Text: "205 DAYS COMPLETE." Flat colour, MS Paint doodle style.

PROMPT 173 [5:44–5:46]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman standing in bright daylight — a large yellow sun in the upper area of the frame radiating twelve long lines. The stickman: medium circle head, dot eyes half-closed with pleasure (the dots surrounded by tiny upward curve marks — eyes wrinkled with joy from the sunlight), a broad upward-curved mouth (true happiness). Body upright, relaxed. Both arms raised outward and slightly upward — a welcoming, soaking-in-the-light pose. Legs apart, stable. Around the figure: small yellow star bursts scattered (light reflecting off everything). Text: "FIRST REAL SUNLIGHT IN 205 DAYS." Flat colour, MS Paint doodle style.

PROMPT 174 [5:46–5:48]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. An infographic summary of the 1972 experiment. A large bordered rectangle (clean double outline). Inside, three rows: ROW 1: "DAYS UNDERGROUND: 205" (black). ROW 2: "DAYS SIFFRE EXPERIENCED: ~100" (red). ROW 3: "SLEEP CYCLE BY END: ~48 HOURS" (navy). Each row has a simple icon to the left — a calendar, a brain, a clock respectively. Clean, readable, impactful. No stickman. Flat colour, MS Paint doodle style.

PROMPT 175 [5:48–5:50]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman being examined by a researcher. The stickman (Siffre): medium circle head, dot eyes directed at the researcher (left), a tired but cooperative neutral mouth. Arms slightly out for examination. Legs apart. The RESEARCHER: medium circle head, dot eyes directed at Siffre, a focused slight-downward professional mouth (intense analysis). Right hand holding a clipboard (small rectangle). Left hand pointing to various parts of Siffre's body (finger extended, pointing at the head, at the torso). Text: "THE DATA WAS EXTRAORDINARY." Flat colour, MS Paint doodle style.

PROMPT 176 [5:50–5:52]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A bold statement panel — a thick-bordered rectangle. Inside: "HE HAD LIVED HALF A YEAR." Below: "AND EXPERIENCED HALF OF IT." The second line slightly larger and bolder. Below that in the rectangle: a simple hourglass icon — the hourglass is filled only halfway (bottom bulb half full). No stickman. Clean graphic statement. Flat colour, MS Paint doodle style.

"""

with open('/home/user/OG-youtube/264_image_prompts.txt', 'a') as f:
    f.write(content)
print("Part 4 appended: Prompts 133-176")
