content = """
══════════════════════════════════════════════════════════
SECTION 7: SUBJECTIVE TIME & CLOSING REFRAME (Prompts 211–264 | 7:00–8:49)
══════════════════════════════════════════════════════════

PROMPT 211 [7:00–7:02]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman standing alone on a thin horizontal line (a tightrope or timeline). To their LEFT: a solid navy rectangle (the cave — the past 205 days). To their RIGHT: white space with a yellow sun (the future — the surface world). The stickman: medium circle head, dot eyes directed rightward (looking toward the light), a neutral but hopeful flat-line mouth. Body upright. Both arms slightly raised at sides (balancing on the line). Legs one in front of the other (on the line). Text: "SIFFRE'S CLOCK HAD DRIFTED COMPLETELY." Flat colour, MS Paint doodle style.

PROMPT 212 [7:02–7:04]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A split frame. TOP HALF: a normal analogue clock — round face, clear numerals 1–12, hands pointing to 9:00 AM. A small yellow sun above it. Labelled "SURFACE REALITY." BOTTOM HALF: the same clock but DISTORTED — the face is now oval (squished), the numbers are irregular spacing (some crowded together, some far apart), the hands point to a wrong time entirely. A navy background behind this lower clock. Labelled "SIFFRE'S INTERNAL CLOCK." A thick black dividing line between the two halves. No stickman. Flat colour, MS Paint doodle style.

PROMPT 213 [7:04–7:06]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A SURFACE TEAM scene. A small room (rectangle outline with door and window). Inside: TWO stickmen — research team members at a table. RESEARCHER 1: medium circle head, dot eyes directed at a wall-mounted large clock, right arm pointing at the clock, left arm on the table. RESEARCHER 2: medium circle head, dot eyes directed at a logbook (rectangle on the table), both arms over the logbook (writing). Both researchers: lab coat indicators (rectangle to knee), neutral focused mouths. A large wall clock shows the surface time clearly. Text: "THE SURFACE TEAM TRACKED EVERY MOMENT." Flat colour, MS Paint doodle style.

PROMPT 214 [7:06–7:08]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman underground (cave walls — navy border, white centre) connected to a stickman on the surface (no border, white space with sun) by a long vertical dotted line running from the cave bottom to the surface top of the frame. The UNDERGROUND STICKMAN: medium circle head, dot eyes sideways (unaware), casual stance — arms at sides, legs apart. The SURFACE STICKMAN: medium circle head, dot eyes directed downward (toward the line and the underground stickman), holding a clipboard, one arm pointing downward. Text beside the dotted line: "SIX MONTHS OF PARALLEL TRACKING." Flat colour, MS Paint doodle style.

PROMPT 215 [7:08–7:10]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A two-column table infographic. LEFT COLUMN header: "SIFFRE SLEPT." RIGHT COLUMN header: "SURFACE SAID." Three rows: ROW 1 — "FELT LIKE: 8 HOURS" | "ACTUAL: 13 HOURS." ROW 2 — "FELT LIKE: DAY 25" | "ACTUAL: DAY 50." ROW 3 — "FELT LIKE: ~100 DAYS" | "ACTUAL: 205 DAYS." All cells have clean black outlines. Left column text in regular black. Right column text in bold navy. No stickman. Clean table format, MS Paint doodle style.

PROMPT 216 [7:10–7:12]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman gesturing toward the viewer — breaking the fourth wall. The stickman: medium circle head, dot eyes directed straight forward (at the camera/viewer), a slight upward-curved mouth (engaging directly with the viewer). RIGHT arm extended forward at 45 degrees, pointing toward the viewer (the "you" gesture — index finger extended from the arm stick, pointing out of the frame). LEFT arm at side. Legs apart, confident, direct stance. A speech bubble: "HERE IS WHAT THIS MEANS FOR YOU." Text is below the stickman. Flat colour, MS Paint doodle style.

PROMPT 217 [7:12–7:14]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. The underground cave scene. A stickman (Siffre) in the cave sleeping on his cot. The stickman: medium circle head lying on the pillow, eyes closed (two short dashes — sleeping), a peaceful but heavy flat-line mouth (deep sleep — heavy). Body horizontal. Arms along sides. Blanket lines over the lower half. From outside the cave (shown via a dotted line above the ground line), a clock face shows the time. The cave stickman is blissfully unaware. A dotted connection line from the surface clock down to the underground sleeper. Text: "SLEEPING 12 TO 14 HOURS — UNAWARE." Flat colour, MS Paint doodle style.

PROMPT 218 [7:14–7:16]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman waking up in the cave, checking their own notes. The stickman: medium circle head, dot eyes directed down at a notebook on a small table (eyes lowered, reading), a neutral concentrated mouth. Right arm extended down to the notebook. Left arm resting. Legs seated on a chair (bent at knee). The notebook is open and has handwritten lines (squiggly marks). A thought bubble from the head shows "I SLEPT 8 HOURS" with a checkmark. But beside the thought bubble: a real clock icon showing 13 hours (with a red arrow pointing to it). The gap between the belief and the reality. Flat colour, MS Paint doodle style.

PROMPT 219 [7:16–7:18]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A simple infographic: the word "SUBJECTIVE TIME" in large bold hand-lettered caps with a decorative thick underline. Below the words: a brief diagram — a stickman's head (circle with dot eyes) on the left, connected by a bracket to a clock face on the right. The clock face is INSIDE the stickman's head circle (it is a head with a clock for a brain). The clock hands are melting slightly (wavy rather than rigid). Text below the bracket: "A PRIVATE CLOCK. CONNECTED TO NOTHING." Flat colour, MS Paint doodle style.

PROMPT 220 [7:18–7:20]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman in a glass jar (a large rectangle/cylinder outline — a jar). The stickman: medium circle head, dot eyes looking outward through the glass (eyes directed toward the viewer), a slightly puzzled-downward mouth. Arms against the jar walls (sticks touching the inside of the glass walls). Legs on the jar floor. The jar is sealed at the top (a lid outline). Outside the jar, the world continues normally — a sun, a clock, other things going on. But the stickman inside is in their own sealed timeline. Text: "SUBJECTIVE TIME — A SEALED WORLD." Flat colour, MS Paint doodle style.

PROMPT 221 [7:20–7:22]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman standing next to TWO clocks. LEFT CLOCK (slightly larger): analogue face, standard time, labelled "EARTH CLOCK." RIGHT CLOCK (slightly smaller): same face but with melting hands, labelled "SIFFRE'S CLOCK." The stickman: medium circle head, dot eyes moving between the two clocks (eyes slightly unfocused — looking at both), a flat straight-line mouth (neutrally processing). Body between the two clocks. Both arms slightly raised (open hands gesturing between the clocks). Legs apart. The two clocks show completely different times. Text: "TWO CLOCKS. ONE PERSON. NO OVERLAP." Flat colour, MS Paint doodle style.

PROMPT 222 [7:22–7:24]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A globe (Earth circle with basic continent marks, circular arrow showing rotation). The globe is on the LEFT side. On the RIGHT side: a stickman with a personal clock on a chain around the neck (a small circle clock hanging from a line around the body line at chest level). The stickman: medium circle head, dot eyes directed downward at their own clock, a puzzled mouth. Between the globe and the stickman: a thick red X — the two are not connected. The globe's rotation clock (shown as a tick on the globe's equator) and the stickman's personal clock are different. Text: "HIS CLOCK AND THE EARTH'S CLOCK: DISCONNECTED." Flat colour, MS Paint doodle style.

PROMPT 223 [7:24–7:26]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A bold panel with the following in large, impactful type: "HIS BODY CLOCK" on line 1. "HAD DRIFTED" on line 2, slightly larger. "SO SEVERELY" on line 3, the largest. Below that: a single small stickman standing at the bottom of the frame, looking up at the text. The stickman: small circle head, dot eyes directed sharply upward (reading the text above), arms hanging at sides, legs together. The text towers above the tiny figure. Flat colour, black on white, MS Paint doodle style.

PROMPT 224 [7:26–7:28]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A split-frame comparison. LEFT HALF: a stickman (Siffre underground) sleeping peacefully, expression suggesting he believes all is normal — medium circle head on pillow, gentle closed-eye dashes, a slight upward mouth (comfortable). The cave walls are the navy borders. A thought bubble above him: "NORMAL NIGHT'S SLEEP ✓." RIGHT HALF: a surface clock showing the actual time has been 14 hours. Bold red text beside the clock: "14 HOURS." The contrast between his belief and reality is the centrepiece. A thick dividing line between the two halves. Flat colour, MS Paint doodle style.

PROMPT 225 [7:28–7:30]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman walking with total confidence in the wrong direction. The stickman: medium circle head, dot eyes forward (self-assured), a confident slight upward-curved mouth. Body upright. Arms swinging with purpose (right arm forward, left arm back — confident walk). Legs in mid-stride. The direction they're walking: TOWARD the edge of a cliff (a simple cliff edge line — the floor line drops off suddenly). The stickman doesn't see the edge. Above the stickman's head: a thought bubble showing "DAY 25 →" as if the destination is nearby. But a sign at the cliff edge reads "ACTUALLY: DAY 58." Text: "HE BELIEVED HE WAS SLEEPING NORMAL NIGHTS." Flat colour, MS Paint doodle style.

PROMPT 226 [7:30–7:32]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A large bold "12–14" in enormous hand-lettered numbers occupying the upper two-thirds of the frame. Below: "HOURS OF SLEEP — EACH NIGHT." Below that in smaller text: "HE CALLED IT: 8." Below that, a red X through the number "8" and a red arrow pointing to "12–14." In the bottom corner: a small stickman with wide shocked eyes. The stickman: small circle head, dot eyes large and wide (shocked), a small open O-mouth, arms raised slightly at sides. Legs together. Flat colour, red and black on white, MS Paint doodle style.

PROMPT 227 [7:32–7:34]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A horizontal sleep bar. The bar spans the width of the frame. A yellow section at the left labelled "ACTUAL ASLEEP" extends from zero to 8 hours. Then the bar continues in red from the 8-hour mark to the 13-hour mark — labelled "UNKNOWN SLEEP TIME." The red portion is unexpected, invisible to Siffre. The bar ends at the 13-hour mark. Below the bar: a stickman standing and looking at it in disbelief — medium circle head, dot eyes directed at the bar (specifically the red portion), a strongly open O-shaped mouth (disbelief). One arm raised pointing at the red section. Flat colour, MS Paint doodle style.

PROMPT 228 [7:34–7:36]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A melting pocket-watch (MS Paint version of Dalí's melting clock — a simple circle clock face but with the edges drooping downward, the numbers sliding off the face, the hands pointing in random directions). The clock face is draped over a simple table edge, dripping. A stickman stands beside it with a confused expression: medium circle head, dot eyes directed at the melting clock, a wavy uncertain mouth line. One arm raised, gesturing toward the clock as if pointing it out. Other arm at side. Legs apart. Text: "SUBJECTIVE TIME — A CLOCK THAT FOLLOWS NO RULES." Flat colour, MS Paint doodle style.

PROMPT 229 [7:36–7:38]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. Bold text panel. Top of frame: "HE WAS LIVING IN" in regular black caps. Centre: "SUBJECTIVE TIME" in enormous, thick, wobbly hand-lettered black characters — the largest text on the screen so far. Below: a small definition box (a thin rectangle): "A PRIVATE CLOCK. INTERIOR. PERSONAL. CONNECTED TO NO EXTERNAL REALITY." No stickman. Pure typographic impact. Flat black on white, MS Paint doodle style.

PROMPT 230 [7:40–7:42]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman holding a globe in one hand and a small clock in the other hand — both things visible, but the stickman's hands are not connecting the two objects to each other. They are held apart. The stickman: medium circle head, dot eyes moving between the two objects (cross-eyed looking at both, slightly lost), a flat-line uncertain mouth. LEFT arm raised holding the globe (circle with continent marks). RIGHT arm raised holding the clock (circle with hands). Both arms at shoulder height. Legs apart. The globe and clock are clearly separate — not connected. Text: "A PRIVATE CLOCK WITH NO RELATIONSHIP TO THE ROTATION OF THE EARTH." Flat colour, MS Paint doodle style.

PROMPT 231 [7:42–7:44]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A bold price-tag shape — the classic rectangular tag with a hole at the top for a string, with the string attached to a hook. The tag reads: "COST OF DARKNESS." Below that on the tag: "≠ DISCOMFORT" with a red X next to "DISCOMFORT." "≠ RESTLESS SLEEP" with a red X. The real cost is NOT listed on the tag — the line below these crossed-out items is BLANK, with a question mark at the end. A small stickman reaches up to look at the tag: small circle head, dot eyes directed at the tag, one arm raised to point at it. Flat colour, red and black on white, MS Paint doodle style.

PROMPT 232 [7:44–7:46]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. The frame is divided into THREE panels. PANEL 1 (crossed out in red): a stickman in a lumpy uncomfortable bed — "DISCOMFORT." Medium circle head, furrowed eyebrow marks, slightly downturned mouth, lying on a lumpy mattress (bumpy rectangle). Red X over the panel. PANEL 2 (crossed out in red): a stickman tossing in bed — "RESTLESS SLEEP." Medium circle head on its side, arms above blanket, legs bent under blanket in an active position. Red X over the panel. PANEL 3 (empty, outlined in bold): just a large question mark inside. Text below: "THE REAL COST IS SOMETHING ELSE." Flat colour, MS Paint doodle style.

PROMPT 233 [7:46–7:48]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman reaching out toward a large ship's anchor — the anchor is large (taking up 30% of the frame), drawn in navy blue, a nautical hook-and-bar design. The stickman: medium circle head, dot eyes directed at the anchor, an earnest slightly desperate open mouth (reaching for something essential). Both arms extended toward the anchor, reaching. Legs stepping toward it. The anchor has the word "LIGHT" written on its body. Below: "THE LOSS OF EXTERNAL LIGHT IS THE LOSS OF YOUR ANCHOR." Flat colour, navy and black on white, MS Paint doodle style.

PROMPT 234 [7:48–7:50]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. An anchor connected to a brain by a thick chain — but the anchor is being PULLED AWAY. The anchor (labelled "LIGHT") is on the left, being pulled leftward (motion lines on the anchor, an arrow showing it moving left). The brain (yellow oval, fold lines) on the right is being dragged leftward too (but resisting — small backward-pull lines on the brain). The chain between them is taut, about to snap. Text: "WHEN LIGHT GOES — THE MOST FUNDAMENTAL ANCHOR LIFTS." Flat colour, navy and yellow on white, MS Paint doodle style.

PROMPT 235 [7:50–7:52]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A body diagram — stickman outline (circle head, body, arms, legs). Inside the body, instead of the clock icon from before, all the cells are shown as tiny squares. Each tiny cell square has a small clock face icon inside it. ALL the tiny clocks inside the cells are ticking normally. A large yellow arrow enters from the top of the head: "LIGHT SIGNAL IN." Below: "EVERY CELL KNOWS THE TIME." The cells with their clocks are the message. Flat colour, MS Paint doodle style.

PROMPT 236 [7:52–7:54]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. The same body diagram but now the large yellow arrow is ABSENT — there is no light signal arrow entering the head anymore. The tiny cell squares inside the body are now shown with their clock icons spinning wildly (clock hands at random angles, motion lines). The clocks are losing sync. A red label over the body: "SIGNAL LOST." Text: "THE SIGNAL THAT TELLS EVERY CELL WHAT MOMENT IT IS — GONE." Flat colour, red and yellow on white, MS Paint doodle style.

PROMPT 237 [7:54–7:56]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A diagram showing a wire (a thick horizontal line) connecting a brain shape on the LEFT to a circle Earth/globe on the RIGHT. The wire has a label along its length: "CALIBRATION WIRE." At the brain end of the wire, a small plug shape (a rectangle with two prong shapes). At the globe end, a socket shape (a rectangle with two hole shapes). The plug is inserted into the socket. Everything connected. A stickman below looks up at the wire — medium circle head, dot eyes directed upward at the wire, a neutral but satisfied mouth (it's working). Flat colour, MS Paint doodle style.

PROMPT 238 [7:56–7:58]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. The same wire diagram but now the plug has been PULLED OUT of the socket — the plug is dangling, not connected. A gap between the plug end and the socket. Sparks at the disconnection point (small star burst shapes in yellow). A bold red "DISCONNECTED" label on the gap. The brain shape on the left now has a dull grey fill instead of yellow (the brain is no longer calibrated). The stickman below: medium circle head, dot eyes wide (alarmed), a strongly downturned mouth. Both arms raised to the sides of the face in alarm. Flat colour, MS Paint doodle style.

PROMPT 239 [7:58–8:00]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. The frame fills with navy gradually from the edges inward — like the darkness closing in on a spotlight. At the very centre of the white spotlight: a stickman standing alone. The stickman: medium circle head, dot eyes directed forward (looking straight ahead into the dark), a flat neutral-to-slightly-downward mouth (the beginning of concern). Arms hanging at sides. Legs together. The dark navy presses in from all four corners, leaving only a circle of white around the stickman. Text in white on the navy edge areas: "WITHOUT IT — REALITY BECOMES INTERIOR." Flat colour, MS Paint doodle style.

PROMPT 240 [8:00–8:02]
Hand-drawn 2D stick-figure / MS Paint doodle style. Dark navy background filling the entire frame. In the centre: the stickman now visible only as a WHITE outline against the dark. The stickman: medium circle head (white circle outline, no fill against the navy), dot eyes (two tiny white dots), a flat-line mouth (a thin white horizontal line). Body a white vertical line. Arms hanging white sticks. Legs white sticks. No external environment — just the figure and the dark. Text in white: "INTERIOR." Just that word. Flat white outline on navy. MS Paint doodle style.

PROMPT 241 [8:02–8:04]
Hand-drawn 2D stick-figure / MS Paint doodle style. Dark navy background. The stickman from the previous frame, but now floating shapes are appearing in the dark around them — three small floating objects beginning to emerge. A small monster shape (just a rough blob with two eyes and teeth marks — very simple doodle) floats to the left. A small photograph-frame shape (rectangle outline) floats to the upper right. A tangled squiggle shape floats below. All drawn in faint white or light grey outlines against the navy. The stickman: medium circle head, dot eyes beginning to notice (eyes slightly wider, directed toward the emerging shapes), a flat uncertain mouth. Text: "YOUR FEARS. YOUR MEMORIES. YOUR UNRESOLVED EMOTIONS." Flat colour, MS Paint doodle style.

PROMPT 242 [8:04–8:06]
Hand-drawn 2D stick-figure / MS Paint doodle style. Dark navy background. The stickman surrounded by the three objects now MORE visible and LARGER than before. The monster blob (left) is larger, with more detail — four teeth, two wide eyes. The photograph frame (right) shows tiny stick figures inside it (memories). The tangled squiggle (below) is bigger and more complex. The stickman: medium circle head, dot eyes wide (both dots large, looking at the shapes around them), a downturned curved mouth (fear response). Arms now slightly raised at sides (defensive posture). Legs pressing together. Text: "THEY FILL THE SPACE THAT LIGHT USED TO HOLD." Flat colour, MS Paint doodle style.

PROMPT 243 [8:06–8:08]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background (returning to light). A stickman in a bedroom at night — a simple room outline (walls, floor, bed visible). The window shows solid navy outside (dark night). The stickman: medium circle head, dot eyes wide open (fully awake), directed upward (staring at the ceiling). Mouth a flat tense line. Body lying in bed. Both arms bent, behind the head (lying-awake thinking position). Legs stretched straight under the blanket. From the head: a dense swirling spiral of thought marks (many tight concentric oval spirals). Text: "THE NEXT TIME YOU LIE AWAKE IN THE DARK." Flat colour, MS Paint doodle style.

PROMPT 244 [8:08–8:10]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. Same bedroom scene. The spiral of thoughts above the stickman's head is even larger now — taking up most of the upper half of the frame. Inside the spiral, tiny floating words: "YESTERDAY," "TOMORROW," "WHAT IF," "WHY DID I," "SHOULD HAVE" — each tiny label in different orientations inside the spiral. The stickman: same position in bed, eyes now even wider (dot circles as large as they can be), mouth now a wavy uncertain line (mind churning). Text: "AND YOUR MIND WON'T LET YOU GO." Flat colour, MS Paint doodle style.

PROMPT 245 [8:10–8:12]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background with a room outline. A stickman stands in the room. Then: a sudden complete blackout — the entire frame inside the room outline goes from white to SOLID NAVY in a single hard cut (depicted as two panels side by side on this single frame — LEFT: white room with stickman visible. RIGHT: navy blackout with the stickman as white outline only). Between the panels: a jagged lightning bolt shape (power outage). Text: "THE NEXT TIME A POWER OUTAGE DROPS YOU INTO TOTAL BLACKNESS." Flat colour, MS Paint doodle style.

PROMPT 246 [8:12–8:14]
Hand-drawn 2D stick-figure / MS Paint doodle style. Full navy background. The stickman is white outline in the dark. A simple power socket on the wall (a flat white rectangle outline with two oval holes — the socket). The socket has lines radiating from it indicating that the power is OUT (no current). Above the socket: a simple light bulb outline — dark, not glowing. A bold white text: "POWER OUT." The stickman: medium circle head (white outline), dot eyes wide (two white dot circles — maximum dilation), a slightly open O-mouth (caught in the sudden dark). One arm slightly raised (the instinctive reaching in the dark). Flat white on navy. MS Paint doodle style.

PROMPT 247 [8:14–8:16]
Hand-drawn 2D stick-figure / MS Paint doodle style. Dark navy background with a narrow band of white at the very bottom of the frame (the ground). The stickman stands in the dark: medium circle head (white circle outline against navy), dot eyes wide (white dots), a slightly raised right arm (beginning to reach toward a potential light source). Left arm at side. Legs apart, grounded. From the stickman's chest — a small glowing ORANGE ember shape in the chest area (the ancient instinct activating). Very faint but visible. Text in white caps: "SOMETHING OLD IN YOUR CHEST." Flat colour, white and orange on navy, MS Paint doodle style.

PROMPT 248 [8:16–8:18]
Hand-drawn 2D stick-figure / MS Paint doodle style. Dark navy background. The orange ember in the stickman's chest is now BRIGHTER — larger, more defined, a small starburst shape of orange. From the ember, a dotted arrow points upward to the stickman's head (the signal going to the brain). From the head, a bold white word emerges from a speech bubble: "MOVE." The stickman: medium circle head (white outline), dot eyes now directed FORWARD and DOWN (looking at the floor — about to move). One leg slightly forward (weight shift — about to take a step). Arms beginning to swing. Text: "FIND LIGHT." Flat colour, white and orange on navy, MS Paint doodle style.

PROMPT 249 [8:18–8:20]
Hand-drawn 2D stick-figure / MS Paint doodle style. Dark navy background. The stickman is now in MOTION — mid-stride. The stickman: medium circle head (white outline), dot eyes directed forward and slightly upward (looking toward an implied light ahead), a set determined straight-line mouth. Body in mid-stride (left leg extended forward, right leg behind, left arm back, right arm forward). Motion lines behind the figure (short horizontal lines suggesting movement). Ahead of the stickman in the far right of the frame: a tiny pinpoint of yellow light (just a tiny yellow dot and two tiny radiating lines). The stickman moves toward it. Text: "DON'T STAY STILL." Flat colour, white and yellow on navy, MS Paint doodle style.

PROMPT 250 [8:20–8:22]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background, bedroom setting. A stickman stands at a window at night — the window shows the dark outside (solid navy rectangle on the other side of the glass). The stickman: medium circle head, dot eyes directed at the dark outside the window (eyes toward the window, wide and alert), a slightly downturned mouth (unsettled). One hand on the windowsill (right arm extended down to rest on the sill). Other arm at side. Legs together. The darkness outside presses against the glass — indicated by the navy rectangle being slightly larger than the window frame, as if pushing inward. Text: "THE NEXT TIME THE DARK OUTSIDE THE WINDOW FEELS HEAVIER THAN IT SHOULD." Flat colour, MS Paint doodle style.

PROMPT 251 [8:22–8:24]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. The same window scene, but a zoom-in on the window glass specifically. The glass of the window (a rectangle outline with a transparent/white fill) now has the dark outside pressing in — the navy rectangle on the other side has stress lines at the corners of the glass (short diagonal crack-lines at each corner, suggesting pressure being applied to the glass from the dark side). A label at the corner: "HEAVIER THAN IT SHOULD BE." No stickman — just the window and the pressing dark. Flat colour, MS Paint doodle style.

PROMPT 252 [8:24–8:26]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman pointing at their own chest — the "that's not what you think it is" gesture. The stickman: medium circle head, dot eyes directed forward (at the viewer), a direct confident mouth (slight upward curve — making a point calmly). RIGHT arm bent, index finger pointing at the chest (the arm stick bent inward, finger touching the centre of the body line). LEFT arm at side. Legs apart, balanced. A bold speech bubble from the stickman: "THAT IS NOT ANXIETY." Below the frame, a label: "THAT IS SOMETHING MUCH OLDER." Flat colour, MS Paint doodle style.

PROMPT 253 [8:26–8:28]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A stickman with a visible brain (the head circle has a cross-section view — the top of the head is open, and a lumpy yellow brain shape is visible inside). The brain has a highlighted section with a label arrow: "ANCIENT PROGRAMME." The programme is a small square box shape inside the brain (like a chip or floppy disk — a small rectangle inside the brain shape). The brain looks very old — indicated by small cobweb lines in the corner of the head circle. The stickman: medium circle head with open top, dot eyes wide (alert — the programme is running), a straight-line mouth. Arms at sides, legs apart. Text: "YOUR BRAIN RUNNING THE OLDEST PROGRAMME IT HAS." Flat colour, MS Paint doodle style.

PROMPT 254 [8:28–8:30]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A computer monitor (a simple rectangle) with a loading progress bar on screen. The progress bar: a white rectangle inside the monitor with a green fill showing 100% completion. Text on the screen: "SURVIVAL.EXE — RUNNING." Below the monitor: a keyboard (a flat rectangle with small grid lines for keys). A stickman sits at the keyboard: medium circle head, dot eyes directed at the monitor screen, a slightly upward mouth (engaged with the programme). Both arms on the keyboard (both sticks resting on the keyboard rectangle). Legs seated. Text: "THE PROGRAMME THAT KEPT EVERY ANCESTOR ALIVE." Flat colour, MS Paint doodle style.

PROMPT 255 [8:30–8:32]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A chain of stickman figures stretching across the full width of the frame — eight figures in a line from LEFT to RIGHT, each holding hands with the next (sticks extended to touch the next figure's stick hand). Figures go from MOST PRIMITIVE (leftmost — the stickman is slightly more hunched, drawn with rough body lines, a slightly more hunched posture) to MOST MODERN (rightmost — upright, clean, identical to the viewer's stickman throughout the video). Each figure has a small circle head, dot eyes, and a straight mouth. The visual is an evolutionary chain. Text: "THE ONE THAT KEPT EVERY ANCESTOR YOU HAVE EVER HAD ALIVE." Flat colour, MS Paint doodle style.

PROMPT 256 [8:32–8:34]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A timeline bar stretching the full width. LEFT end: "200,000 YEARS AGO." RIGHT end: "NOW." Along the bar, small navy rectangles mark the NIGHTS of those 200,000 years — they are densely packed, too many to count, covering most of the bar. The sheer number of night-marks is the visual message. A small stickman at the very RIGHT end of the bar (the present): small circle head, dot eyes looking LEFT along the bar (looking back at all those nights), a neutral mouth. Arms at sides. Text: "200,000 YEARS OF NIGHTS." Flat colour, MS Paint doodle style.

PROMPT 257 [8:34–8:36]
Hand-drawn 2D stick-figure / MS Paint doodle style. Dark navy background (night scene, prehistoric). A campfire in the lower centre of the frame — the campfire drawn as three orange triangle flames above a small log arrangement (two crossed lines for logs, three upward-pointing triangle flames above). Around the campfire: THREE stickman ancestor figures sitting in a semi-circle. ANCESTOR 1 (left): small circle head, dot eyes directed at the fire, arms resting on bent knees, sitting cross-legged. ANCESTOR 2 (centre, slightly larger): same posture but arms wrapped around self (slightly cold). ANCESTOR 3 (right): same but head tilted slightly (watching the dark outside the firelight). All have simple features, neutral-to-slightly-alert expressions. The area beyond the firelight is solid navy — the unknown dark. Text in white: "THEY HAD NO GUARANTEE." Flat colour, MS Paint doodle style.

PROMPT 258 [8:36–8:38]
Hand-drawn 2D stick-figure / MS Paint doodle style. Dark navy background. The campfire from before is now very small — just a tiny flame in the lower corner. The rest of the frame is navy darkness. The three ancestor stickmen are barely visible — only their white outlines against the navy, eyes catching the tiny firelight (two tiny dot reflections per figure visible). The darkness dominates. One ancestor stickman (rightmost): medium circle head turned outward to face the dark directly — dot eyes wide, directed into the deep navy. A very slight forward lean in the posture (vigilance, scanning for threats). Text in white: "200,000 YEARS OF NIGHTS THEY HAD NO GUARANTEE THEY WOULD SURVIVE." Flat colour, MS Paint doodle style.

PROMPT 259 [8:38–8:40]
Hand-drawn 2D stick-figure / MS Paint doodle style. White background. A bold infographic: a horizontal bar timeline of human history. The bar is wide and long. On the LEFT, 99% of the bar is labelled "NO ARTIFICIAL LIGHT" (filled in navy blue). On the RIGHT, a tiny sliver (1% of the bar) is labelled "ARTIFICIAL LIGHT — 150 YEARS" (filled in yellow). The yellow sliver is almost invisible relative to the navy span. Text above: "FOR 200,000 YEARS — DARKNESS MEANT DANGER." A small arrow points to the tiny yellow sliver: "WE ARE HERE." No stickman. Flat colour, MS Paint doodle style.

PROMPT 260 [8:40–8:42]
Hand-drawn 2D stick-figure / MS Paint doodle style. Dark navy background. A stickman in total darkness — only white outline visible. The stickman: medium circle head (white circle outline against navy), eyes VERY wide (two large white circles for the eye whites, with tiny black pupil dots — maximum dilation). A flat-line mouth (held very still — listening for threats). Body completely still. Arms at sides, not moving. Legs together, frozen in place. The darkness presses in from all sides. A very faint texture in the navy (tiny light-grey irregular marks — suggesting the imagination is beginning to fill the dark). Text in white: "IF YOU STAYED IN THAT DARK LONG ENOUGH." Flat colour, MS Paint doodle style.

PROMPT 261 [8:42–8:44]
Hand-drawn 2D stick-figure / MS Paint doodle style. Dark navy background. The same frozen stickman, but now the faint texture around the stickman is becoming slightly more visible — the tiny marks in the navy dark are now slightly larger and more defined, suggesting shapes beginning to form (but not yet fully visible). The stickman: same white outline, same wide eyes, same frozen posture. But the dot eyes are now directed slightly to one side (something in the dark has caught the attention). A very faint question mark in the dark to the right (white dotted outline — barely visible). Text in white: "IT WOULD STOP SHOWING YOU WHAT IS THERE." Flat colour, MS Paint doodle style.

PROMPT 262 [8:44–8:46]
Hand-drawn 2D stick-figure / MS Paint doodle style. Nearly full black background — darker than any previous navy, approaching true black. In the dark: the real objects of the cave (a rock shape, a branch shape, a pool outline) are drawn in DOTTED FADING LINES — they are disappearing, dissolving into the black. The stickman stands at the centre: medium circle head (very faint white outline — barely visible), the dot eyes directed outward (looking at the fading real objects). The real world is becoming invisible. White dotted text at the bottom: "THE REAL THINGS FADE." Flat colour (black and faint white dots), MS Paint doodle style.

PROMPT 263 [8:46–8:48]
Hand-drawn 2D stick-figure / MS Paint doodle style. Full black background — the darkest frame of the entire video. Floating in the black: THREE ghostly shapes in white dotted outlines. SHAPE 1 (upper left): a large floating EYE — an oval with an iris circle and a wide pupil, floating with no body, no face. SHAPE 2 (upper right): a HAND reaching from nowhere — five stick fingers extended from a palm shape, reaching toward the stickman. SHAPE 3 (lower centre): an AMORPHOUS BLOB — an irregular shape with six spikes, two jagged eye-hole shapes, and a wide zigzag mouth (like a monster but vague and shapeless). Each shape has a small red label: "NOT REAL." The stickman at the very bottom of the frame: tiny circle head (white outline), dot eyes staring upward at the three shapes (eyes at the widest they have ever been — enormous with terror), both arms raised defensively in front of the chest (both sticks raised at chest height forming a cross — protecting oneself). Legs spread wide apart (bracing against what's being seen). Flat colour, MS Paint doodle style.

PROMPT 264 [8:47–8:49]
Hand-drawn 2D stick-figure / MS Paint doodle style. Full black background. Minimal. At the centre of the frame: a single line of text in clean bold white caps: "IT WOULD START SHOWING YOU WHAT IS NOT." Below the text: nothing — just black silence. No stickman. No shapes. Just the words and the dark. The text is the only element in the entire frame. The period at the end of the sentence is slightly larger than the rest of the punctuation — deliberate, final. Flat white text on black. MS Paint doodle style. The last image of the video.

══════════════════════════════════════════════════════════
END OF ALL 264 IMAGE PROMPTS
Total Runtime: 529 seconds | Average per Prompt: ~2 seconds
Channel: The Ancient Brain
Video: What Happens to the Human Brain During Total Darkness
Visual Style: Hand-drawn 2D stick-figure / MS Paint doodle aesthetic
All human characters: STRICTLY stickman throughout
══════════════════════════════════════════════════════════
"""

with open('/home/user/OG-youtube/264_image_prompts.txt', 'a') as f:
    f.write(content)
print("Part 6 appended: Prompts 211-264 — FILE COMPLETE")
